Repository scverse/anndata, pull requests merged in 2023-08, with the labels that each got.

#1084 Update machine image for GPU CI
  .cirun.yml
  .github/workflows/test-gpu.yml
  docs/contributing.md
  docs/release-notes/0.10.0.md
Labels: run-gpu-ci

#1089 Run GPU ci on main
  .github/workflows/test-gpu.yml
Labels: dev process, run-gpu-ci

#1073 Remove unused imports
  anndata/__init__.py
  anndata/_core/anndata.py
  anndata/_core/merge.py
  anndata/_core/raw.py
  anndata/_core/views.py
  anndata/_io/__init__.py
  anndata/_io/h5ad.py
  anndata/_io/read.py
  anndata/_io/specs/__init__.py
  anndata/_io/specs/methods.py
  anndata/_io/utils.py
  anndata/_io/write.py
  anndata/_io/zarr.py
  anndata/compat/__init__.py
  anndata/experimental/multi_files/__init__.py
  anndata/experimental/pytorch/__init__.py
  anndata/experimental/pytorch/_annloader.py
  anndata/tests/conftest.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_deprecations.py
  anndata/tests/test_hdf5_backing.py
  anndata/tests/test_inplace_subset.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_io_partial.py
  anndata/tests/test_readwrite.py
  anndata/tests/test_structured_arrays.py
  anndata/tests/test_utils.py
  anndata/tests/test_views.py
  anndata/utils.py
  benchmarks/benchmarks/readwrite.py
  benchmarks/benchmarks/utils.py
  docs/conf.py
  pyproject.toml
Labels: run-gpu-ci

#1092 Add preemptible
  .cirun.yml
Labels: run-gpu-ci

#1094 Fix mandatory GPU tests
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-pr-milestoned.yml
  .github/workflows/test-gpu.yml
Labels: skip-gpu-ci

#1065 Add GitHub and code copy button
  README.md
  anndata/_core/anndata.py
  docs/conf.py
  pyproject.toml
Labels: skip-gpu-ci

#1100 Fix benchmarks and pandas compat
  .github/workflows/benchmark.yml
  anndata/tests/test_views.py
  benchmarks/asv.conf.json
  pyproject.toml
Labels: skip-gpu-ci

#1102 Update main CI python version to 3.11 (25% faster)
  .azure-pipelines.yml
  .github/workflows/test-gpu.yml
  .readthedocs.yml
Labels: dev process, run-gpu-ci

#1101 Backport PR #1097 on branch 0.9.x (pepy fix)
  README.md
Labels: skip-gpu-ci

#1055 Use __notes__ for IO exceptions
  anndata/__init__.py
  anndata/_io/specs/methods.py
  anndata/_io/utils.py
  anndata/compat/__init__.py
  anndata/compat/exceptiongroups.py
  anndata/tests/helpers.py
  anndata/tests/test_helpers.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_io_utils.py
  anndata/tests/test_readwrite.py
  docs/release-notes/0.10.0.md
  pyproject.toml
Labels: enhancement, topic: error messages 🤬, run-gpu-ci

#1079 Dask Distributed Write Fix For Zarr
  anndata/_io/specs/methods.py
  anndata/tests/test_dask.py
  pyproject.toml
Labels: skip-gpu-ci

#1108 Deprecate anndata.read
  anndata/__init__.py
  anndata/tests/test_deprecations.py
  docs/release-notes/0.10.0.md
Labels: backend: hdf5, skip-gpu-ci

#1109 Add codespell integration and fix found typos: added configuration and github workflow
  .github/workflows/codespell.yml
  .pre-commit-config.yaml
  anndata/_core/aligned_mapping.py
  anndata/_core/anndata.py
  anndata/_core/merge.py
  anndata/_io/read.py
  anndata/_io/specs/methods.py
  anndata/_io/specs/registry.py
  anndata/compat/__init__.py
  anndata/experimental/_dispatch_io.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  anndata/tests/helpers.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_helpers.py
  anndata/tests/test_uns.py
  benchmarks/README.md
  benchmarks/benchmarks/utils.py
  docs/api.md
  docs/contributing.md
  docs/release-notes/0.6.0.md
  docs/release-notes/0.7.2.md
  docs/release-notes/0.9.0.md
  pyproject.toml
Labels: skip-gpu-ci
