Repository scverse/anndata, pull requests merged in 2023-07, with the labels that each got.

#1044 Pin awkward
  pyproject.toml
Labels: dev process, type: awkward array 😐

#1047 Backport of #1039 to 0.9.x
  README.md
Labels: docs

#1049 Fix 0.9.2 release notes
  docs/release-notes/0.9.2.md
Labels: no milestone

#864 Centralize pytest options
  .azure-pipelines.yml
Labels: dev process

#1054 Update bug-report template to include dependencies
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: dev process, no milestone

#1040 Fix for awkward 2.3
  anndata/_core/views.py
  anndata/tests/test_awkward.py
  docs/release-notes/0.9.2.md
  pyproject.toml
Labels: topic: views 👀, Bug 🐛, type: awkward array 😐

#1069 Backport PR #1040 on branch 0.9.x (Fix for awkward 2.3)
  anndata/_core/views.py
  anndata/tests/test_awkward.py
  docs/release-notes/0.9.2.md
  pyproject.toml
Labels: topic: views 👀, Bug 🐛, type: awkward array 😐

#1066 Add cupy support + CI
  .cirun.yml
  .github/workflows/test-gpu.yml
  anndata/_core/anndata.py
  anndata/_core/merge.py
  anndata/_core/raw.py
  anndata/_core/views.py
  anndata/_io/specs/methods.py
  anndata/compat/__init__.py
  anndata/tests/helpers.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_gpu.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_views.py
  anndata/utils.py
  conftest.py
  docs/release-notes/0.10.0.md
  pyproject.toml
Labels: topic: gpu
