Repository scverse/anndata, pull requests merged in 2023-03, with the labels that each got.

#928 Add sphinx-opengraph
  docs/conf.py
  pyproject.toml
Labels: docs

#930 Backport PR #928 on branch 0.9.x (Add sphinx-opengraph)
  docs/conf.py
  pyproject.toml
Labels: docs

#939 Fix adata.raw.to_adata() not having obs, obsm from the parent
  anndata/_core/anndata.py
  anndata/tests/test_raw.py
  docs/release-notes/0.9.0.md
Labels: Bug 🐛

#943 Remove new feature warning from anndata.concat
  anndata/_core/merge.py
Labels: docs, topic: combining

#945 Backport PR #943 on branch 0.9.x (Remove new feature warning from anndata.concat)
  anndata/_core/merge.py
Labels: docs, topic: combining
