Repository scverse/anndata, pull requests merged in 2023-10, with the labels that each got.

#1131 Optimize contiguous sparse slicing
  anndata/_core/index.py
  anndata/_core/sparse_dataset.py
  benchmarks/benchmarks/sparse_dataset.py
  docs/release-notes/0.10.0.md
Labels: performance 🐌, topic: backed, run-gpu-ci, type: sparse 🫥

#1136 (fix): add compatibility for anndata with sparse_dataset
  anndata/_core/anndata.py
  anndata/tests/test_backed_sparse.py
Labels: topic: backed, type: sparse 🫥, skip-gpu-ci

#1153 Just deprecate dtype argument
  anndata/_core/anndata.py
  anndata/tests/test_deprecations.py
  docs/release-notes/0.10.0.md
Labels: dev process, run-gpu-ci

#1156 Error on mixed device concatenation
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
Labels: run-gpu-ci

#1161 Add-concat-on-disk-examples
  anndata/_core/anndata.py
  anndata/experimental/merge.py
  anndata/tests/test_concatenate_disk.py
  pyproject.toml
Labels: skip-gpu-ci

#1162 Add zarr examples to fileformat docs
  docs/conf.py
  docs/fileformat-prose.md
  docs/release-notes/0.10.0.md
  pyproject.toml
Labels: docs, backend: zarr, skip-gpu-ci

#1165 Prep 0.10
  docs/release-notes/0.10.0.md
Labels: dev process, skip-gpu-ci

#1166 Start 0.10.1
  docs/release-notes/0.10.1.md
  docs/release-notes/release-latest.md
Labels: dev process, skip-gpu-ci

#1168 start 0.11
  docs/release-notes/0.11.0.md
  docs/release-notes/release-latest.md
Labels: dev process, skip-gpu-ci

#1171 Fix error when concatenating object to categorical
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.1.md
Labels: topic: combining, skip-gpu-ci

#1172 Backport PR #1171 on branch 0.10.x (Fix error when concatenating object to categorical)
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.1.md
Labels: topic: combining, run-gpu-ci

#1173 Prep 0.10.1
  docs/release-notes/0.10.1.md
Labels: skip-gpu-ci

#1174 Backport PR #1173 on branch 0.10.x (Prep 0.10.1)
  docs/release-notes/0.10.1.md
Labels: skip-gpu-ci

#1175 Start release notes for 0.10.2
  docs/release-notes/0.10.2.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1176 Backport PR #1175 on branch 0.10.x (Start release notes for 0.10.2)
  docs/release-notes/0.10.2.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1178 Backport PR #1177 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1169 Fix: Dense OOC Concat With Aligned Elements Memory Issue
  anndata/experimental/merge.py
Labels: performance 🐌, skip-gpu-ci

#1179 Backport PR #1169 on branch 0.10.x (Fix: Dense OOC Concat With Aligned Elements Memory Issue)
  anndata/experimental/merge.py
Labels: performance 🐌, skip-gpu-ci

#1181 Fix bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: no milestone, skip-gpu-ci

#1183 Fewer warnings
  anndata/_core/aligned_mapping.py
  anndata/tests/helpers.py
  anndata/tests/test_io_warnings.py
  anndata/tests/test_views.py
Labels: testing, dev process, run-gpu-ci

#1187 Backport PR #1183 on branch 0.10.x (Fewer warnings)
  anndata/_core/aligned_mapping.py
  anndata/tests/helpers.py
  anndata/tests/test_io_warnings.py
  anndata/tests/test_views.py
Labels: testing, dev process, run-gpu-ci

#1188 Add blank issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: dev process, skip-gpu-ci

#1185 Backwards compat for SparseDataset usage
  anndata/_core/sparse_dataset.py
  anndata/tests/test_deprecations.py
  docs/release-notes/0.10.2.md
Labels: topic: backed, Bug 🐛, type: sparse 🫥, skip-gpu-ci

#1190 Backport PR #1185 on branch 0.10.x (Backwards compat for SparseDataset usage)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_deprecations.py
  docs/release-notes/0.10.2.md
Labels: topic: backed, Bug 🐛, type: sparse 🫥, skip-gpu-ci

#1189 Fix some public warnings
  anndata/_core/merge.py
  anndata/compat/__init__.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  docs/release-notes/0.10.2.md
Labels: Bug 🐛, skip-gpu-ci

#1191 Backport PR #1189 on branch 0.10.x (Fix some public warnings)
  anndata/_core/merge.py
  anndata/compat/__init__.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  docs/release-notes/0.10.2.md
Labels: Bug 🐛, skip-gpu-ci

#1193 Backport more user-facing fixes from #1182
  anndata/_io/h5ad.py
  anndata/_io/utils.py
  anndata/tests/test_hdf5_backing.py
  docs/release-notes/0.10.2.md
Labels: Bug 🐛, skip-gpu-ci

#1194 Backport PR #1193 on branch 0.10.x (Backport more user-facing fixes from #1182)
  anndata/_io/h5ad.py
  anndata/_io/utils.py
  anndata/tests/test_hdf5_backing.py
  docs/release-notes/0.10.2.md
Labels: Bug 🐛, skip-gpu-ci

#1192 Prep release notes
  docs/release-notes/0.10.2.md
Labels: dev process, run-gpu-ci

#1196 Backport PR #1192 on branch 0.10.x (Prep release notes)
  docs/release-notes/0.10.2.md
Labels: dev process, run-gpu-ci

#1199 Backport PR #1198 on branch 0.10.x (Start 0.10.3)
  docs/release-notes/0.10.3.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1182 Treat warnings as errors in tests
  .azure-pipelines.yml
  anndata/_core/aligned_mapping.py
  anndata/_core/anndata.py
  anndata/_core/merge.py
  anndata/_io/read.py
  anndata/_io/utils.py
  anndata/_io/zarr.py
  anndata/compat/__init__.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  anndata/tests/test_awkward.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_concatenate_disk.py
  anndata/tests/test_dask.py
  anndata/tests/test_dask_view_mem.py
  anndata/tests/test_deprecations.py
  anndata/tests/test_hdf5_backing.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_io_warnings.py
  anndata/tests/test_layers.py
  anndata/tests/test_raw.py
  anndata/tests/test_readwrite.py
  anndata/utils.py
  conftest.py
  docs/benchmark-read-write.ipynb
  docs/concatenation.rst
  docs/release-notes/0.10.3.md
  docs/release-notes/0.6.0.md
  pyproject.toml
Labels: run-gpu-ci

#1207 Backport PR #1182 on branch 0.10.x (Treat warnings as errors in tests)
  .azure-pipelines.yml
  anndata/_core/aligned_mapping.py
  anndata/_core/anndata.py
  anndata/_core/merge.py
  anndata/_io/read.py
  anndata/_io/utils.py
  anndata/_io/zarr.py
  anndata/compat/__init__.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  anndata/tests/test_awkward.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_concatenate_disk.py
  anndata/tests/test_dask.py
  anndata/tests/test_dask_view_mem.py
  anndata/tests/test_deprecations.py
  anndata/tests/test_hdf5_backing.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_io_warnings.py
  anndata/tests/test_layers.py
  anndata/tests/test_raw.py
  anndata/tests/test_readwrite.py
  anndata/utils.py
  conftest.py
  docs/benchmark-read-write.ipynb
  docs/concatenation.rst
  docs/conf.py
  docs/release-notes/0.10.3.md
  docs/release-notes/0.6.0.md
  pyproject.toml
Labels: run-gpu-ci

#1209 Specify deprecated theme option
  docs/conf.py
Labels: skip-gpu-ci

#1211 Skip pandas release causing infinite recursion
  docs/release-notes/0.10.3.md
  pyproject.toml
Labels: skip-gpu-ci

#1212 Backport PR #1211 on branch 0.10.x (Skip pandas release causing infinite recursion)
  docs/release-notes/0.10.3.md
  pyproject.toml
Labels: skip-gpu-ci

#1216 Backport PR #1215 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1213 Add release workflow
  .github/workflows/publish.yml
Labels: dev process, skip-gpu-ci

#1217 Backport PR #1213 on branch 0.10.x (Add release workflow)
  .github/workflows/publish.yml
Labels: dev process, skip-gpu-ci

#1218 Prepare 0.10.3 release
  docs/release-notes/0.10.3.md
Labels: skip-gpu-ci

#1219 Backport PR #1218 on branch 0.10.x (Prepare 0.10.3 release)
  docs/release-notes/0.10.3.md
Labels: skip-gpu-ci

#1221 Backport PR #1220 on branch 0.10.x (Start 0.10.4)
  docs/release-notes/0.10.4.md
  docs/release-notes/release-latest.md
Labels: skip-gpu-ci
