Repository scverse/anndata, pull requests merged in 2023-09, with the labels that each got.

#1061 Restrict files written by tests
  .azure-pipelines.yml
  .gitignore
  anndata/compat/__init__.py
  conftest.py
Labels: no milestone, run-gpu-ci

#1123 Consolidate IO tests
  anndata/tests/test_readwrite.py
Labels: skip-gpu-ci

#1121 Fix shape inference for X=None
  anndata/_core/anndata.py
  anndata/_core/raw.py
  anndata/tests/test_base.py
  anndata/tests/test_raw.py
  anndata/tests/test_views.py
  anndata/tests/test_x.py
  docs/release-notes/0.10.0.md
  docs/release-notes/0.9.3.md
  docs/release-notes/release-latest.md
Labels: skip-gpu-ci

#765 (feat): Backed zarr and hdf5 sparse matrices (separate from backed mode)
  anndata/_core/anndata.py
  anndata/_core/file_backing.py
  anndata/_core/raw.py
  anndata/_core/sparse_dataset.py
  anndata/_io/h5ad.py
  anndata/_io/specs/methods.py
  anndata/_io/utils.py
  anndata/experimental/__init__.py
  anndata/experimental/merge.py
  anndata/experimental/multi_files/_anncollection.py
  anndata/tests/helpers.py
  anndata/tests/test_backed_sparse.py
  anndata/tests/test_deprecations.py
  anndata/utils.py
  docs/api.md
  docs/release-notes/0.10.0.md
Labels: topic: io, topic: backed, backend: zarr, topic: exported functions, run-gpu-ci

#1114 Add support for sparse arrays inside dask arrays
  anndata/_core/anndata.py
  anndata/_core/index.py
  anndata/_core/merge.py
  anndata/_io/specs/methods.py
  anndata/_io/specs/registry.py
  anndata/compat/__init__.py
  anndata/tests/helpers.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_transpose.py
  anndata/tests/test_views.py
  anndata/utils.py
  docs/release-notes/0.10.0.md
Labels: enhancement, topic: io, run-gpu-ci, type: sparse 🫥, type: dask array

#1126 Remove deprecated type argument to anndata constructor
  anndata/_core/anndata.py
  anndata/tests/test_deprecations.py
  docs/release-notes/0.10.0.md
Labels: breaking change ‼️, run-gpu-ci

#1129 Doc preparation for 0.10.0rc1
  anndata/experimental/merge.py
  docs/api.md
  docs/index.md
  docs/release-notes/0.10.0.md
  docs/release-notes/index.md
  docs/release-notes/release-latest.md
Labels: run-gpu-ci

#1130 typo in link
  docs/release-notes/0.10.0.md
Labels: skip-gpu-ci

#1145 Fix `ConvertType`
  anndata/experimental/multi_files/_anncollection.py
Labels: skip-gpu-ci

#1150 Remove unsupported param from `.cirun.yml`
  .cirun.yml
Labels: run-gpu-ci
