Repository scverse/anndata, pull requests merged in 2023-02, with the labels that each got.

#869 Views on dask arrays copy the array into memory
  anndata/_core/views.py
  anndata/tests/test_dask_view_mem.py
  pyproject.toml
Labels: bug, performance, topic: views 👀

#891 Use ruff
  .flake8
  .pre-commit-config.yaml
  anndata/_core/anndata.py
  pyproject.toml
Labels: dev process

#904 Fix outer concat when generating fill obsm values
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
Labels: topic: combining, Bug 🐛

#915 Allow dim_len of records to be the number of fields.
  anndata/tests/test_awkward.py
  anndata/utils.py
Labels: topic: combining, Bug 🐛

#920 Myst, but actually this time
  README.md
  README.rst
  docs/api.md
  docs/benchmarks.md
  docs/benchmarks.rst
  docs/contributing.md
  docs/contributing.rst
  docs/index.md
  docs/index.rst
  docs/interoperability.md
  docs/interoperability.rst
  docs/news.md
  docs/news.rst
  docs/release-notes/0.4.0.md
  docs/release-notes/0.4.0.rst
  docs/release-notes/0.5.0.md
  docs/release-notes/0.5.0.rst
  docs/release-notes/0.6.0.md
  docs/release-notes/0.6.0.rst
  docs/release-notes/0.7.0.md
  docs/release-notes/0.7.0.rst
  docs/release-notes/0.7.2.md
  docs/release-notes/0.7.2.rst
  docs/release-notes/0.7.3.md
  docs/release-notes/0.7.3.rst
  docs/release-notes/0.7.4.md
  docs/release-notes/0.7.4.rst
  docs/release-notes/0.7.5.md
  docs/release-notes/0.7.5.rst
  docs/release-notes/0.7.6.md
  docs/release-notes/0.7.6.rst
  docs/release-notes/0.7.7.md
  docs/release-notes/0.7.7.rst
  docs/release-notes/0.7.8.md
  docs/release-notes/0.7.8.rst
  docs/release-notes/0.8.0.md
  docs/release-notes/0.8.0.rst
  docs/release-notes/0.8.1.md
  docs/release-notes/0.8.1.rst
  docs/release-notes/0.9.0.md
  docs/release-notes/0.9.0.rst
  docs/release-notes/index.md
  docs/release-notes/index.rst
  docs/release-notes/release-latest.md
  docs/release-notes/release-latest.rst
  docs/tutorials/index.md
  docs/tutorials/index.rst
  pyproject.toml
Labels: docs, dev process
