Repository scverse/anndata, pull requests merged in 2023-11, with the labels that each got.

#1226 Fix na_action compatibility
  anndata/compat/__init__.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1227 Backport PR #1226 on branch 0.10.x (Fix na_action compatibility)
  anndata/compat/__init__.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1229 Backport PR #1228 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1197 Remove old modules
  anndata/core.py
  anndata/readwrite.py
  docs/release-notes/0.11.0.md
  pyproject.toml
Labels: topic: api, breaking change ‼️, skip-gpu-ci

#1232 Backport PR #1231 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1230 Patch AnnData.__sizeof__() for backed datasets
  anndata/_core/anndata.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1234 Backport PR #1230 on branch 0.10.x (Patch AnnData.__sizeof__() for backed datasets)
  anndata/_core/anndata.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1238 Backport PR #1237 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1239 Fix a few minor documentation typos
  docs/concatenation.rst
  docs/fileformat-prose.md
Labels: no milestone, skip-gpu-ci

#1214 Centralize warning config
  .azure-pipelines.yml
  conftest.py
  pyproject.toml
Labels: run-gpu-ci

#1242 Backport PR #1214 on branch 0.10.x (Centralize warning config)
  .azure-pipelines.yml
  conftest.py
  pyproject.toml
Labels: run-gpu-ci
