Repository scverse/anndata, pull requests merged in 2023-12, with the labels that each got.

#1243 (fix): subsetting with empty list
  anndata/_core/index.py
  anndata/tests/test_views.py
  docs/release-notes/0.10.4.md
Labels: run-gpu-ci

#1252 Improve aligned mapping errors
  anndata/_core/aligned_mapping.py
  anndata/tests/test_layers.py
  anndata/tests/test_obsmvarm.py
  anndata/tests/test_obspvarp.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1253 Backport PR #1252 on branch 0.10.x (Improve aligned mapping errors)
  anndata/_core/aligned_mapping.py
  anndata/tests/test_layers.py
  anndata/tests/test_obsmvarm.py
  anndata/tests/test_obspvarp.py
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1255 (fix): index check for newer `numpy` versions in `sparse_dataset`
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: backend: hdf5, backend: zarr, Bug 🐛, skip-gpu-ci

#1259 Backport PR #1255 on branch 0.10.x ((fix): index check for newer `numpy` versions in `sparse_dataset`)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: backend: hdf5, backend: zarr, Bug 🐛, skip-gpu-ci

#1260 Update config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: dev process, skip-gpu-ci

#1265 (fix): `copy` on `BackedSparseMatrix` for `zarr`
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: topic: backed, backend: zarr, Bug 🐛, skip-gpu-ci

#1268 Backport PR #1265 on branch 0.10.x ((fix): `copy` on `BackedSparseMatrix` for `zarr`)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.4.md
Labels: topic: backed, backend: zarr, Bug 🐛, skip-gpu-ci

#1275 Switch to ruff formatting
  .gitignore
  .pre-commit-config.yaml
  anndata/_core/merge.py
  anndata/_core/sparse_dataset.py
  anndata/experimental/multi_files/_anncollection.py
  docs/benchmark-read-write.ipynb
  pyproject.toml
Labels: skip-gpu-ci

#1276 Backport PR #1275 on branch 0.10.x (Switch to ruff formatting)
  .gitignore
  .pre-commit-config.yaml
  anndata/_core/merge.py
  anndata/_core/sparse_dataset.py
  anndata/experimental/multi_files/_anncollection.py
  docs/benchmark-read-write.ipynb
  pyproject.toml
Labels: skip-gpu-ci

#1279 Backport PR #1278 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci
