Repository scverse/anndata, pull requests merged in 2024-02, with the labels that each got.

#1355 Backport PR #1354 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1362 (chore): `anndata._config` -> `anndata._settings`
  anndata/__init__.py
  anndata/_core/anndata.py
  anndata/_settings.py
  anndata/tests/test_base.py
  anndata/tests/test_settings.py
Labels: skip-gpu-ci

#1363 moves .ci to ci
  .github/workflows/test-gpu.yml
  ci/gpu_ci.yml
Labels: run-gpu-ci

#1364 Backport PR #1363 on branch 0.10.x (moves .ci to ci)
  .github/workflows/test-gpu.yml
  ci/gpu_ci.yml
Labels: skip-gpu-ci

#1370 Backport PR #1369 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1367 Turn on code cov patch annotations
  .codecov.yml
Labels: dev process, skip-gpu-ci

#1371 Backport PR #1367 on branch 0.10.x (Turn on code cov patch annotations)
  .codecov.yml
Labels: dev process, skip-gpu-ci

#1366 (fix): calculate mean slice correctly for sparse boolean->slice optimization
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: backend: hdf5, topic: backed, backend: zarr, Bug 🐛, type: sparse 🫥, skip-gpu-ci

#1372 Backport PR #1366 on branch 0.10.x ((fix): calculate mean slice correctly for sparse boolean->slice optimization)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: backend: hdf5, topic: backed, backend: zarr, Bug 🐛, type: sparse 🫥, skip-gpu-ci

#1314 Test against mindeps
  .azure-pipelines.yml
  anndata/experimental/merge.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_io_warnings.py
  ci/scripts/min-deps.py
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: dev process, run-gpu-ci

#1374 Backport PR #1314 on branch 0.10.x (Test against mindeps)
  .azure-pipelines.yml
  anndata/experimental/merge.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_io_warnings.py
  ci/scripts/min-deps.py
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: dev process, run-gpu-ci

#1375 fix mixed up release notes
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
Labels: docs, dev process, skip-gpu-ci

#1376 Backport PR #1375 on branch 0.10.x (fix mixed up release notes)
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
Labels: docs, dev process, skip-gpu-ci

#1373 Test against and list support for python 3.12
  .azure-pipelines.yml
  .github/workflows/benchmark.yml
  .readthedocs.yml
  anndata/tests/test_layers.py
  anndata/tests/test_readwrite.py
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1377 Backport PR #1373 on branch 0.10.x (Test against and list support for python 3.12)
  .azure-pipelines.yml
  .github/workflows/benchmark.yml
  .readthedocs.yml
  anndata/tests/test_layers.py
  anndata/tests/test_readwrite.py
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1380 Backport PR #1379 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1384 try unpinning node
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1386 Backport PR #1384 on branch 0.10.x (try unpinning node)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1365 (feat): allow boolean indices to pass down to `X`
  anndata/_core/index.py
  anndata/_core/views.py
  anndata/tests/test_backed_sparse.py
  anndata/tests/test_views.py
  benchmarks/benchmarks/sparse_dataset.py
  docs/release-notes/0.10.6.md
Labels: enhancement, backend: hdf5, topic: backed, backend: zarr, skip-gpu-ci

#1387 Backport PR #1365 on branch 0.10.x ((feat): allow boolean indices to pass down to `X`)
  anndata/_core/index.py
  anndata/_core/views.py
  anndata/tests/test_backed_sparse.py
  anndata/tests/test_views.py
  benchmarks/benchmarks/sparse_dataset.py
  docs/release-notes/0.10.6.md
Labels: enhancement, backend: hdf5, topic: backed, backend: zarr, skip-gpu-ci
