Repository scverse/anndata, pull requests merged in 2024-03, with the labels that each got.

#1348 Write dask arrays with 64bit indptr
  anndata/_core/sparse_dataset.py
  anndata/_io/specs/methods.py
  anndata/tests/test_backed_sparse.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.6.md
Labels: topic: backed, Bug 🐛, run-gpu-ci, type: sparse 🫥

#1393 Backport PR #1348 on branch 0.10.x (Write dask arrays with 64bit indptr)
  anndata/_core/sparse_dataset.py
  anndata/_io/specs/methods.py
  anndata/tests/test_backed_sparse.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.6.md
Labels: topic: backed, Bug 🐛, run-gpu-ci, type: sparse 🫥

#1396 remove circularity and implicit module members
  anndata/__init__.py
  anndata/_core/aligned_df.py
  anndata/_core/anndata.py
  anndata/_core/raw.py
  anndata/_io/__init__.py
  anndata/tests/test_raw.py
Labels: dev process, skip-gpu-ci

#1397 Backport PR #1396 on branch 0.10.x (remove circularity and implicit module members)
  anndata/__init__.py
  anndata/_core/aligned_df.py
  anndata/_core/anndata.py
  anndata/_core/raw.py
  anndata/_io/__init__.py
  anndata/tests/test_raw.py
Labels: dev process, skip-gpu-ci

#1395 Invalid type of X ValueError lists unclear accepted types
  anndata/_core/anndata.py
  anndata/tests/test_base.py
  docs/release-notes/0.10.6.md
Labels: skip-gpu-ci

#1398 Backport PR #1395 on branch 0.10.x (Invalid type of X ValueError lists unclear accepted types)
  anndata/_core/anndata.py
  anndata/tests/test_base.py
  docs/release-notes/0.10.6.md
Labels: skip-gpu-ci

#1402 Update `to_df` docstrings
  anndata/_core/anndata.py
  docs/release-notes/0.10.6.md
Labels: docs, skip-gpu-ci

#1406 Backport PR #1402 on branch 0.10.x (Update `to_df` docstrings)
  anndata/_core/anndata.py
  docs/release-notes/0.10.6.md
Labels: docs, skip-gpu-ci

#1407 prep-0.10.6
  docs/release-notes/0.10.6.md
Labels: docs, dev process, skip-gpu-ci

#1411 Pin array-api-compat!=1.5
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: run-gpu-ci

#1412 Backport PR #1411 on branch 0.10.x (Pin array-api-compat!=1.5)
  docs/release-notes/0.10.6.md
  pyproject.toml
Labels: run-gpu-ci

#1408 Backport PR #1407 on branch 0.10.x (prep-0.10.6)
  docs/release-notes/0.10.6.md
Labels: docs, dev process, run-gpu-ci

#1409 Start 0.10.7
  docs/release-notes/0.10.7.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, run-gpu-ci

#1413 Backport PR #1409 on branch 0.10.x (Start 0.10.7)
  docs/release-notes/0.10.7.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, run-gpu-ci

#1415 Fix BaseCompressedSparseDataset.group type annotation
  anndata/_core/sparse_dataset.py
  docs/conf.py
Labels: docs, dev process, skip-gpu-ci

#1420 Backport PR #1419 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  anndata/_core/merge.py
  anndata/_types.py
  anndata/tests/test_annot.py
  anndata/tests/test_awkward.py
  anndata/tests/test_concatenate.py
  anndata/tests/test_dask.py
  anndata/tests/test_deprecations.py
  anndata/tests/test_io_conversion.py
  anndata/tests/test_io_elementwise.py
  anndata/tests/test_x.py
  benchmarks/benchmarks/readwrite.py
Labels: skip-gpu-ci

#1421 Handle numcodecs bug for encoding read-only string array
  anndata/_io/specs/methods.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.7.md
Labels: run-gpu-ci

#1422 Backport PR #1421 on branch 0.10.x (Handle numcodecs bug for encoding read-only string array)
  anndata/_io/specs/methods.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.7.md
Labels: run-gpu-ci

#1416 Backport PR #1415 on branch 0.10.x (Fix BaseCompressedSparseDataset.group type annotation)
  anndata/_core/sparse_dataset.py
  docs/conf.py
Labels: docs, dev process, skip-gpu-ci

#1423 Run CI with uv
  .azure-pipelines.yml
Labels: dev process, skip-gpu-ci

#1424 Backport PR #1423 on branch 0.10.x (Run CI with uv)
  .azure-pipelines.yml
Labels: dev process, skip-gpu-ci

#1425 use uv for gpu tests
  .github/workflows/test-gpu.yml
  ci/gpu_ci.yml
Labels: dev process, run-gpu-ci

#1426 Backport PR #1425 on branch 0.10.x (use uv for gpu tests)
  .github/workflows/test-gpu.yml
  ci/gpu_ci.yml
Labels: dev process, run-gpu-ci

#1428 Backport PR #1427 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1435 Fix pre-release tests
  .azure-pipelines.yml
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1432 (fix): optimize subsetting dask array
  .azure-pipelines.yml
  anndata/_core/index.py
  docs/release-notes/0.10.7.md
Labels: skip-gpu-ci

#1436 Backport PR #1435 on branch 0.10.x (Fix pre-release tests)
  .azure-pipelines.yml
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1439 (fix): update CZI file urls for merge test
  anndata/experimental/merge.py
Labels: skip-gpu-ci

#1440 Backport PR #1439 on branch 0.10.x ((fix): update CZI file urls for merge test)
  anndata/experimental/merge.py
Labels: skip-gpu-ci

#1437 Backport PR #1432: (fix): optimize subsetting dask array
  .azure-pipelines.yml
  anndata/_core/index.py
  docs/release-notes/0.10.7.md
Labels: skip-gpu-ci

#1443 Backport PR #1442 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1445 update mamba
  .github/workflows/codespell.yml
  .github/workflows/publish.yml
  .github/workflows/test-gpu.yml
Labels: dev process, run-gpu-ci

#1446 Backport PR #1445 on branch 0.10.x (update mamba)
  .github/workflows/codespell.yml
  .github/workflows/publish.yml
  .github/workflows/test-gpu.yml
Labels: dev process, run-gpu-ci
