Repository scverse/anndata, pull requests merged in 2024-10, with the labels that each got.

#1701 Backport PR #1700 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1702 Simplify roundtrip io tests
  tests/test_readwrite.py
Labels: dev process, skip-gpu-ci

#1703 Backport PR #1702 on branch 0.10.x (Simplify roundtrip io tests)
  tests/test_readwrite.py
Labels: dev process, skip-gpu-ci

#1712 (chore): remove python 3.9
  .azure-pipelines.yml
  docs/release-notes/1712.breaking.md
  hatch.toml
  pyproject.toml
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/utils.py
  src/anndata/_types.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  src/anndata/typing.py
  tests/test_backed_hdf5.py
  tests/test_concatenate.py
  tests/test_io_dispatched.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1713 (chore): generate 0.11.0rc3 release notes
  docs/release-notes/0.11.0rc3.md
  docs/release-notes/1712.breaking.md
Labels: no milestone, skip-gpu-ci

#1714 (fix): gpu ci uses max version from `pyproject.toml`
  .github/workflows/test-gpu.yml
Labels: no milestone, run-gpu-ci

#1717 Fix AnnData citation
  README.md
Labels: dev process, skip-gpu-ci

#1718 Backport PR #1717 on branch 0.10.x (Fix AnnData citation)
  README.md
Labels: dev process, skip-gpu-ci

#1719 (fix): correct default fill values for dask-sparse
  docs/release-notes/1719.bugfix.md
  src/anndata/_core/merge.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1720 Fix docs links
  docs/conf.py
  docs/release-notes/0.11.0rc1.md
Labels: dev process, skip-gpu-ci

#1725 remove label in ci
  .github/workflows/test-gpu.yml
Labels: dev process

#1727 Backport PR #1725: remove label in ci
  .github/workflows/test-gpu.yml
Labels: skip-gpu-ci

#1728 Backport PR #1705 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1730 Fix GH actions benchmark run
  .github/workflows/benchmark.yml
Labels: dev process, skip-gpu-ci, benchmark

#1732 Backport PR #1730 on branch 0.10.x (Fix GH actions benchmark run)
  .github/workflows/benchmark.yml
Labels: dev process, skip-gpu-ci, benchmark

#1729 (feat): support ellipsis indexing
  docs/conf.py
  docs/release-notes/1729.feature.md
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/compat/__init__.py
  tests/conftest.py
  tests/test_backed_sparse.py
  tests/test_views.py
Labels: skip-gpu-ci

#1734 Backport PR #1729: (feat): support ellipsis indexing
  docs/conf.py
  docs/release-notes/1729.feature.md
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/compat/__init__.py
  tests/conftest.py
  tests/test_backed_sparse.py
  tests/test_views.py
Labels: skip-gpu-ci
