Repository scverse/anndata, pull requests merged in 2024-12, with the labels that each got.

#1785 (fix): upper bound `pytest`
  pyproject.toml
  src/anndata/_io/specs/registry.py
Labels: skip-gpu-ci

#1788 Backport PR #1785 on branch 0.11.x ((fix): upper bound `pytest`)
  pyproject.toml
  src/anndata/_io/specs/registry.py
Labels: skip-gpu-ci

#1791 (fix): clarify release docs
  docs/contributing.md
Labels: skip-gpu-ci

#1724 Keep .X when setting filename to None
  src/anndata/_core/file_backing.py
  tests/test_backed_hdf5.py
Labels: skip-gpu-ci

#1794 Backport PR #1793 on branch 0.11.x ((fix): scanpy/numba install in `test-gpu.yml`)
  .github/workflows/test-gpu.yml
Labels: run-gpu-ci

#1795 Backport PR #1724 on branch 0.11.x (Keep .X when setting filename to None)
  src/anndata/_core/file_backing.py
  tests/test_backed_hdf5.py
Labels: skip-gpu-ci

#1783 IO: treat arrays with an empty shape like scalars when writing
  docs/release-notes/1783.bugfix.md
  src/anndata/_io/specs/methods.py
  src/anndata/_io/utils.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1797 Backport PR #1784 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1746 (fix): raise error on non-integer floating types in iterables
  docs/release-notes/1746.bugfix.md
  src/anndata/_core/index.py
  tests/test_views.py
Labels: topic: indexing, Bug 🐛, skip-gpu-ci

#1780 (fix): use dask array for missing element in dask concatenation
  src/anndata/_core/merge.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1790 (performance): speedup for `zarr`-based sparse indexing
  docs/release-notes/1790.performance.md
  src/anndata/_core/sparse_dataset.py
Labels: performance 🐌, backend: zarr, type: sparse 🫥, skip-gpu-ci, benchmark

#1800 Backport PR #1780 on branch 0.11.x ((fix): use dask array for missing element in dask concatenation)
  src/anndata/_core/merge.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1801 Backport PR #1790 on branch 0.11.x ((performance): speedup for `zarr`-based sparse indexing)
  docs/release-notes/1790.performance.md
  src/anndata/_core/sparse_dataset.py
Labels: performance 🐌, backend: zarr, type: sparse 🫥, skip-gpu-ci, benchmark

#1805 Issue template: Use session-info2
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: dev process, no milestone, skip-gpu-ci

#1808 Backport PR #1807 on branch 0.11.x (Fix min-deps hatch config)
  .azure-pipelines.yml
  .github/workflows/test-gpu.yml
  .gitignore
  ci/constraints.txt
  ci/scripts/min-deps.py
  ci/scripts/towncrier_automation.py
  hatch.toml
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1806 Fix backed sparse matrix compat with scipy 1.15
  docs/release-notes/1806.bugfix.md
  src/anndata/_core/sparse_dataset.py
  src/anndata/compat/__init__.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1809 Backport PR #1806 on branch 0.11.x (Fix backed sparse matrix compat with scipy 1.15)
  docs/release-notes/1806.bugfix.md
  src/anndata/_core/sparse_dataset.py
  src/anndata/compat/__init__.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
Labels: skip-gpu-ci
