Repository scverse/anndata, pull requests merged in 2024-06, with the labels that each got.

#1244 Add semantic dimension identifier to concat API
  docs/release-notes/0.11.0.md
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/experimental/merge.py
  src/anndata/utils.py
  tests/test_awkward.py
  tests/test_concatenate.py
  tests/test_helpers.py
Labels: skip-gpu-ci

#1509 (chore): change boolean settings names to use `should`
  src/anndata/_core/anndata.py
  src/anndata/_settings.py
  tests/test_base.py
Labels: topic: api, skip-gpu-ci

#1507 (feat): add `check_uniqueness` setting
  docs/release-notes/0.11.0.md
  src/anndata/_core/anndata.py
  src/anndata/_settings.py
  tests/test_base.py
Labels: enhancement, topic: api, type: dataframe 🧮, skip-gpu-ci

#1515 Fix settings
  src/anndata/_settings.py
  tests/test_settings.py
Labels: dev process, skip-gpu-ci

#1511 Backport PR #1510: [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1518 Add triage label for new issues
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: dev process, skip-gpu-ci

#1521 Lint tests
  pyproject.toml
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  tests/conftest.py
  tests/test_anncollection.py
  tests/test_awkward.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_dask_view_mem.py
  tests/test_deprecations.py
  tests/test_gpu.py
  tests/test_hdf5_backing.py
  tests/test_helpers.py
  tests/test_inplace_subset.py
  tests/test_io_conversion.py
  tests/test_io_elementwise.py
  tests/test_layers.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_repr.py
  tests/test_settings.py
  tests/test_views.py
Labels: dev process, skip-gpu-ci

#1524 Format sparse_dataset code
  .azure-pipelines.yml
  ci/scripts/min-deps.py
  pyproject.toml
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/methods.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/utils.py
  tests/test_backed_sparse.py
  tests/test_io_dispatched.py
Labels: dev process, skip-gpu-ci

#1525 Backport PR #1524: Format sparse_dataset code
  .azure-pipelines.yml
  ci/scripts/min-deps.py
  pyproject.toml
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/methods.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/utils.py
  tests/test_backed_sparse.py
  tests/test_io_dispatched.py
Labels: dev process, skip-gpu-ci

#1487 Switch conftest to plugin
  pyproject.toml
  src/testing/anndata/__init__.py
  src/testing/anndata/_pytest.py
  src/testing/anndata/py.typed
Labels: run-gpu-ci

#1527 Backport PR #1487: Switch conftest to plugin
  pyproject.toml
  src/testing/anndata/__init__.py
  src/testing/anndata/_helpers.py
  src/testing/anndata/_pytest.py
  src/testing/anndata/py.typed
  tests/test_layers.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1528 Fix numpy check
  src/testing/anndata/_helpers.py
  tests/test_layers.py
  tests/test_readwrite.py
Labels: dev process, skip-gpu-ci

#1514 (fix): fix for new `scipy.sparse` matrix strings in `sparse_dataset` docstring tests
  docs/release-notes/0.10.8.md
  src/anndata/_core/sparse_dataset.py
Labels: skip-gpu-ci

#1522 Backport PR #1521: Lint tests
  pyproject.toml
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  tests/conftest.py
  tests/test_anncollection.py
  tests/test_awkward.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_dask_view_mem.py
  tests/test_deprecations.py
  tests/test_gpu.py
  tests/test_hdf5_backing.py
  tests/test_helpers.py
  tests/test_inplace_subset.py
  tests/test_io_conversion.py
  tests/test_io_elementwise.py
  tests/test_layers.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_repr.py
  tests/test_views.py
Labels: dev process, skip-gpu-ci

#1529 Backport PR #1514 on branch 0.10.x ((fix): fix for new `scipy.sparse` matrix strings in `sparse_dataset` docstring tests)
  docs/release-notes/0.10.8.md
  src/anndata/_core/sparse_dataset.py
Labels: skip-gpu-ci

#1533 Backport PR #1531: [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1534 Prepare v0.10.8
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/release-latest.md
  src/anndata/_io/zarr.py
Labels: skip-gpu-ci

#1535 Backport PR #1534 on branch 0.10.x (Prepare v0.10.8)
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/release-latest.md
  src/anndata/_io/zarr.py
Labels: skip-gpu-ci

#1516 Coerce np.matrix instances to np.ndarray
  docs/release-notes/0.10.9.md
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/storage.py
  src/anndata/utils.py
  tests/test_base.py
  tests/test_io_elementwise.py
  tests/test_views.py
Labels: skip-gpu-ci

#1536 Backport PR #1516: Coerce np.matrix instances to np.ndarray
  docs/release-notes/0.10.9.md
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/storage.py
  src/anndata/utils.py
  tests/test_base.py
  tests/test_io_elementwise.py
  tests/test_views.py
Labels: skip-gpu-ci

#1532 (fix): allow setting `X` as sparse when `X` is dense view
  docs/release-notes/0.10.9.md
  src/anndata/_core/anndata.py
  tests/test_x.py
Labels: topic: views 👀, Bug 🐛, type: sparse 🫥, skip-gpu-ci

#1538 Backport PR #1532 on branch 0.10.x ((fix): allow setting X as sparse when X is dense view)
  docs/release-notes/0.10.9.md
  src/anndata/_core/anndata.py
  tests/test_x.py
Labels: skip-gpu-ci

#1540 (fix): upper bound `numpy` only for `gpu`
  docs/release-notes/0.10.9.md
  pyproject.toml
Labels: topic: gpu, run-gpu-ci

#1542 (fix): `pr` number for `gpu` `numpy` version fix
  docs/release-notes/0.10.9.md
Labels: skip-gpu-ci

#1541 Backport PR #1540 on branch 0.10.x ((fix): upper bound `numpy` only for `gpu`)
  docs/release-notes/0.10.9.md
  pyproject.toml
Labels: topic: gpu, run-gpu-ci

#1544 Backport PR #1543 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1545 (fix): don't try to write `pandas` `string` type in `test_scanpy_krumsiek11`
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1546 Backport PR #1545 on branch 0.10.x ((fix): don't try to write `pandas` `string` type in `test_scanpy_krumsiek11`)
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1537 Fix assigning and initializing with h5py datasets
  src/anndata/_core/anndata.py
  src/anndata/_core/storage.py
  src/anndata/tests/helpers.py
  tests/test_backed_dense.py
  tests/test_backed_hdf5.py
Labels: skip-gpu-ci
