Repository scverse/anndata, pull requests merged in 2024-11, with the labels that each got.

#1736 Fix saving of AwkwardArrayView
  docs/release-notes/1736.bugfix.md
  src/anndata/_io/specs/methods.py
  tests/test_awkward.py
Labels: skip-gpu-ci

#1738 Backport PR #1736 on branch 0.10.x (Fix saving of AwkwardArrayView)
  docs/release-notes/1736.bugfix.md
  src/anndata/_io/specs/methods.py
  tests/test_awkward.py
Labels: skip-gpu-ci

#1739 Backport PR #1626: (chore): automation of towncrier release process (+ other towncrier automation fixes)
  ci/scripts/towncrier_automation.py
  docs/contributing.md
  pyproject.toml
  src/anndata/logging.py
Labels: skip-gpu-ci

#1741 Revert "Backport PR #1626: (chore): automation of towncrier release process (+ other towncrier automation fixes)"
  ci/scripts/towncrier_automation.py
  docs/contributing.md
  pyproject.toml
  src/anndata/logging.py
Labels: skip-gpu-ci

#1742 (chore): generate 0.11.0 release notes
  docs/release-notes/0.11.0.md
  docs/release-notes/0.11.0rc3.md
  docs/release-notes/1719.bugfix.md
  docs/release-notes/1729.feature.md
  docs/release-notes/1736.bugfix.md
Labels: no milestone, skip-gpu-ci

#1747 Add PYI lints
  pyproject.toml
  src/anndata/_core/anndata.py
  src/anndata/_types.py
Labels: skip-gpu-ci

#1748 Backport PR #1747 on branch 0.11.x (Add PYI lints)
  pyproject.toml
  src/anndata/_core/anndata.py
  src/anndata/_types.py
Labels: skip-gpu-ci

#1743 (fix): lazy chunking respects -1
  docs/release-notes/1743.bugfix.md
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/registry.py
  tests/test_io_elementwise.py
Labels: Bug 🐛, skip-gpu-ci, type: dask array

#1745 (chore): unbound dask
  docs/release-notes/1725.bugfix.md
  pyproject.toml
  tests/conftest.py
Labels: skip-gpu-ci

#1750 Backport PR #1743 on branch 0.11.x ((fix): lazy chunking respects -1)
  docs/release-notes/1743.bugfix.md
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/registry.py
  tests/test_io_elementwise.py
Labels: Bug 🐛, skip-gpu-ci, type: dask array

#1751 Backport PR #1745 on branch 0.11.x ((chore): unbound dask)
  docs/release-notes/1725.bugfix.md
  pyproject.toml
  tests/conftest.py
Labels: skip-gpu-ci

#1752 Merge 0.11 docs with rcs
  docs/release-notes/0.11.0.md
  docs/release-notes/0.11.0rc1.md
  docs/release-notes/0.11.0rc2.md
  docs/release-notes/0.11.0rc3.md
Labels: dev process, skip-gpu-ci

#1753 Backport PR #1752 on branch 0.11.x (Merge 0.11 docs with rcs)
  docs/release-notes/0.11.0.md
  docs/release-notes/0.11.0rc1.md
  docs/release-notes/0.11.0rc2.md
  docs/release-notes/0.11.0rc3.md
Labels: dev process, skip-gpu-ci

#1754 (fix): resolve cupy import error on `cupy-cuda12x<0.13`
  docs/release-notes/1754.bugfix.md
  src/anndata/compat/__init__.py
Labels: skip-gpu-ci

#1759 (chore): generate 0.11.1 release notes
  docs/release-notes/0.11.1.md
  docs/release-notes/1725.bugfix.md
  docs/release-notes/1743.bugfix.md
  docs/release-notes/1754.bugfix.md
Labels: no milestone, skip-gpu-ci

#1761 (chore): generate 0.11.1 release notes
  docs/release-notes/0.11.1.md
  docs/release-notes/1725.bugfix.md
  docs/release-notes/1743.bugfix.md
  docs/release-notes/1754.bugfix.md
Labels: skip-gpu-ci

#1762 Fix towncrier automation PR body
  ci/scripts/towncrier_automation.py
Labels: dev process, skip-gpu-ci

#1763 Backport PR #1761 on branch main ((chore): generate 0.11.1 release notes)
  docs/release-notes/0.11.1.md
  docs/release-notes/1725.bugfix.md
  docs/release-notes/1743.bugfix.md
  docs/release-notes/1754.bugfix.md
Labels: no milestone, skip-gpu-ci

#1764 Backport PR #1762: Fix towncrier automation PR body
  ci/scripts/towncrier_automation.py
Labels: dev process, skip-gpu-ci

#1765 (feat): restrict release branches in automation
  ci/scripts/towncrier_automation.py
Labels: skip-gpu-ci

#1771 Backport PR #1765 on branch 0.11.x ((feat): restrict release branches in automation)
  ci/scripts/towncrier_automation.py
Labels: skip-gpu-ci

#1773 Backport PR #1772 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1774 (fix): python debugger dask h5 meta array
  src/anndata/_io/specs/lazy_methods.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1775 Backport PR #1774: (fix): python debugger dask h5 meta array
  src/anndata/_io/specs/lazy_methods.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1758 Harmonize min-deps script with scanpy
  ci/scripts/min-deps.py
Labels: skip-gpu-ci

#1776 Backport PR #1758 on branch 0.11.x (Harmonize min-deps script with scanpy)
  ci/scripts/min-deps.py
Labels: skip-gpu-ci

#1744 (fix): cache arrays in `BaseCompressedSparseDataset`
  docs/release-notes/1744.bugfix.md
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/lazy_methods.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
Labels: Bug 🐛, type: sparse 🫥, skip-gpu-ci, type: dask array

#1778 Backport PR #1744 on branch 0.11.x ((fix): cache arrays in `BaseCompressedSparseDataset`)
  docs/release-notes/1744.bugfix.md
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/lazy_methods.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
Labels: Bug 🐛, type: sparse 🫥, skip-gpu-ci, type: dask array

#1781 Backport PR #1779 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci
