Repository scverse/anndata, pull requests merged in 2024-04, with the labels that each got.

#1449 Backport PR #1441 on branch 0.10.x ((fix): use in-memory scipy sparse for non-overriden methods)
  anndata/_core/sparse_dataset.py
  anndata/tests/helpers.py
  anndata/tests/test_backed_sparse.py
  benchmarks/benchmarks/readwrite.py
  benchmarks/benchmarks/sparse_dataset.py
  docs/release-notes/0.10.7.md
  pyproject.toml
Labels: skip-gpu-ci, benchmark

#1453 Backport PR #1452 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1454 Prep 0.10.7
  docs/release-notes/0.10.7.md
Labels: dev process, run-gpu-ci

#1455 Backport PR #1454 on branch 0.10.x (Prep 0.10.7)
  docs/release-notes/0.10.7.md
Labels: dev process, run-gpu-ci

#1461 Backport PR #1460 on branch 0.10.x (Remove pytest_8_raises shim)
  src/anndata/tests/helpers.py
  src/anndata/tests/test_helpers.py
  src/anndata/tests/test_io_elementwise.py
  src/anndata/tests/test_io_utils.py
  src/anndata/tests/test_readwrite.py
Labels: testing, dev process, run-gpu-ci

#1458 Start 0.10.8
  docs/release-notes/0.10.8.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1463 Backport PR #1458 on branch 0.10.x (Start 0.10.8)
  docs/release-notes/0.10.8.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1462 lower required pytest version
  pyproject.toml
Labels: dev process, run-gpu-ci

#1464 Backport PR #1462 on branch 0.10.x (lower required pytest version)
  pyproject.toml
Labels: dev process, run-gpu-ci

#1465 Update coverage upload
  .azure-pipelines.yml
Labels: dev process, skip-gpu-ci

#1450 Fix benchmark params
  benchmarks/benchmarks/readwrite.py
  benchmarks/benchmarks/sparse_dataset.py
Labels: dev process, skip-gpu-ci, benchmark

#1466 Backport PR #1465 on branch 0.10.x (Update coverage upload)
  .azure-pipelines.yml
Labels: dev process, skip-gpu-ci

#1467 Backport PR #1450 on branch 0.10.x (Fix benchmark params)
  benchmarks/benchmarks/readwrite.py
  benchmarks/benchmarks/sparse_dataset.py
Labels: dev process, skip-gpu-ci, benchmark

#1472 Backport PR #1471 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1478 Backport PR #1477 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1028 (feat): Support for scipy.sparse.{csr,csc}_array
  .gitignore
  docs/release-notes/0.11.0.md
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/views.py
  src/anndata/_io/specs/methods.py
  src/anndata/compat/__init__.py
  src/anndata/tests/conftest.py
  src/anndata/tests/helpers.py
  src/anndata/tests/test_backed_sparse.py
  src/anndata/tests/test_base.py
  src/anndata/tests/test_concatenate.py
  src/anndata/tests/test_concatenate_disk.py
  src/anndata/tests/test_hdf5_backing.py
  src/anndata/tests/test_inplace_subset.py
  src/anndata/tests/test_io_dispatched.py
  src/anndata/tests/test_readwrite.py
  src/anndata/tests/test_views.py
  src/anndata/tests/test_x.py
  src/anndata/utils.py
Labels: enhancement, run-gpu-ci

#1468 update doc-string for sparse dataset
  docs/release-notes/0.10.8.md
  src/anndata/_core/sparse_dataset.py
Labels: docs, skip-gpu-ci

#1485 Backport PR #1484 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci
