Repository scverse/anndata, pull requests merged in 2024-05, with the labels that each got.

#1486 Backport PR #1459 on branch 0.10.x (Move tests out of package)
  .azure-pipelines.yml
  .codecov.yml
  conftest.py
  pyproject.toml
  src/anndata/tests/conftest.py
  tests/conftest.py
  tests/data/adata-comments.tsv
  tests/data/adata.csv
  tests/data/archives/readme.md
  tests/data/archives/v0.7.0/adata.h5ad
  tests/data/archives/v0.7.0/adata.zarr.zip
  tests/data/archives/v0.7.8/adata.h5ad
  tests/data/archives/v0.7.8/adata.zarr.zip
  tests/data/excel.xlsx
  tests/data/umi_tools.tsv.gz
  tests/test_anncollection.py
  tests/test_annot.py
  tests/test_awkward.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_dask_view_mem.py
  tests/test_deprecations.py
  tests/test_get_vector.py
  tests/test_gpu.py
  tests/test_hdf5_backing.py
  tests/test_helpers.py
  tests/test_inplace_subset.py
  tests/test_io_backwards_compat.py
  tests/test_io_conversion.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_io_utils.py
  tests/test_io_warnings.py
  tests/test_layers.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_repr.py
  tests/test_structured_arrays.py
  tests/test_transpose.py
  tests/test_uns.py
  tests/test_utils.py
  tests/test_views.py
  tests/test_x.py
Labels: skip-gpu-ci

#1491 Backport PR #1490 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1495 Backport PR #1493 on branch 0.10.x ((fix): write out 64 bit indptr for `concat_on_disk` when appropriate)
  docs/release-notes/0.10.8.md
  src/anndata/_io/specs/methods.py
  src/anndata/experimental/merge.py
  tests/test_io_elementwise.py
Labels: topic: combining, backend: hdf5, topic: backed, skip-gpu-ci

#1497 Backport PR #1496 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1499 Numpy 2 compatibility
  docs/release-notes/0.10.8.md
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/zarr.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/tests/_helpers.py
  tests/test_layers.py
  tests/test_obspvarp.py
  tests/test_readwrite.py
Labels: run-gpu-ci

#1500 Backport PR #1499: Numpy 2 compatibility
  docs/release-notes/0.10.8.md
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/zarr.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/tests/_helpers.py
  tests/test_layers.py
  tests/test_obspvarp.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1506 (fix): spelling issues for CI
  benchmarks/README.md
Labels: skip-gpu-ci

#1508 Backport PR #1506 on branch 0.10.x ((fix): spelling issues for CI)
  benchmarks/README.md
Labels: skip-gpu-ci
