Repository scverse/anndata, pull requests merged in 2024-08, with the labels that each got.

#1575 Backport PR #1574 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  docs/conf.py
  docs/news.md
Labels: skip-gpu-ci

#1580 (fix): upper bound `dask` by 2024.8.0
  docs/release-notes/0.10.9.md
  pyproject.toml
Labels: skip-gpu-ci

#1581 Backport PR #1580 on branch 0.10.x ((fix): upper bound `dask` by 2024.8.0)
  docs/release-notes/0.10.9.md
  pyproject.toml
Labels: skip-gpu-ci

#1147 Fix: Large number of dataframe columns (H5py Attr Limit)
  docs/release-notes/0.10.9.md
  src/anndata/_io/specs/methods.py
  src/anndata/compat/__init__.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1582 Backport PR #1147 on branch 0.10.x (Fix: Large number of dataframe columns (H5py Attr Limit))
  docs/release-notes/0.10.9.md
  src/anndata/_io/specs/methods.py
  src/anndata/compat/__init__.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1474 Make `strings_to_categoricals` upon `.write()` optional
  src/anndata/_io/h5ad.py
  src/anndata/_io/zarr.py
Labels: skip-gpu-ci

#1585 Revert "Backport PR #1474: Make `strings_to_categoricals` upon `.write()` optional (#1584)"
  src/anndata/_io/h5ad.py
  src/anndata/_io/zarr.py
Labels: skip-gpu-ci

#1587 (chore): release note + use verb for #1474
  docs/release-notes/0.11.0.md
  src/anndata/_io/h5ad.py
  src/anndata/_io/zarr.py
Labels: skip-gpu-ci

#1583 Fix links
  docs/conf.py
  docs/extensions/patch_sphinx_toolbox_autoprotocol.py
  docs/release-notes/0.10.9.md
  docs/release-notes/0.11.0.md
  src/anndata/_settings.py
  tests/test_settings.py
Labels: dev process, skip-gpu-ci

#1588 (fix): comment out broken benchmark
  benchmarks/benchmarks/readwrite.py
Labels: dev process, skip-gpu-ci, benchmark

#1590 Backport PR #1588 on branch 0.10.x ((fix): comment out broken benchmark)
  benchmarks/benchmarks/readwrite.py
Labels: dev process, skip-gpu-ci, benchmark

#1586 (fix): setting `index` on `DataFrameView`
  docs/release-notes/0.10.9.md
  src/anndata/_core/views.py
  tests/test_views.py
Labels: skip-gpu-ci

#1591 Backport PR #1586 on branch 0.10.x ((fix): setting index on DataFrameView)
  docs/release-notes/0.10.9.md
  src/anndata/_core/views.py
  tests/test_views.py
Labels: skip-gpu-ci

#1594 (fix): minimum `python` version `3.11` for`NamedTuple` with `Generic`
  src/anndata/_settings.py
Labels: skip-gpu-ci

#1595 Backport PR #1592 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1603 Backport PR #1601 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  src/testing/anndata/_pytest.py
  tests/conftest.py
  tests/test_anncollection.py
  tests/test_backed_dense.py
  tests/test_backed_hdf5.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_dask_view_mem.py
  tests/test_deprecations.py
  tests/test_gpu.py
  tests/test_helpers.py
  tests/test_io_elementwise.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_repr.py
  tests/test_views.py
Labels: skip-gpu-ci

#1605 Fix heading anchors in relnotes
  .azure-pipelines.yml
  docs/conf.py
  docs/extensions/patch_myst_cite.py
  docs/news.md
  docs/references.rst
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
Labels: dev process, skip-gpu-ci

#1606 Backport PR #1605 on branch 0.10.x (Fix heading anchors in relnotes)
  .azure-pipelines.yml
  docs/conf.py
  docs/extensions/patch_myst_cite.py
  docs/news.md
  docs/references.rst
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
Labels: dev process, skip-gpu-ci

#1609 Backport PR #1589: (fix): disallow using dataframes with multi index columns
  docs/release-notes/0.10.9.md
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/storage.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_annot.py
  tests/test_base.py
  tests/test_obsmvarm.py
Labels: skip-gpu-ci

#1613 Backport PR #1604 on branch 0.10.x ((feat): use towncrier for changelog automations)
  .gitignore
  ci/scripts/min-deps.py
  docs/conf.py
  docs/extensions/release_notes.py
  docs/index.md
  docs/release-notes/0.10.9.md
  docs/release-notes/1147.bugfix.md
  docs/release-notes/1501.bugfix.md
  docs/release-notes/1504.performance.md
  docs/release-notes/1516.bugfix.md
  docs/release-notes/1532.bugfix.md
  docs/release-notes/1540.bugfix.md
  docs/release-notes/1557.doc.md
  docs/release-notes/1580.bugfix.md
  docs/release-notes/1586.bugfix.md
  docs/release-notes/1589.bugfix.md
  docs/release-notes/index.md
  hatch.toml
  pyproject.toml
Labels: skip-gpu-ci

#1611 (chore): v0.11 fragments
  docs/release-notes/0.11.0.md
  docs/release-notes/1028.feature.md
  docs/release-notes/1197.breaking.md
  docs/release-notes/1244.feature.md
  docs/release-notes/1270.feature.md
  docs/release-notes/1340.feature.md
  docs/release-notes/1469.feature.md
  docs/release-notes/1474.feature.md
  docs/release-notes/1507.feature.md
  docs/release-notes/1550.feature.md
  pyproject.toml
Labels: docs, skip-gpu-ci

#1614 Backport PR #1610 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1612 (fix): use correct implementation of `StorageType` and resolve name conflict
  src/anndata/_core/storage.py
  src/anndata/_io/specs/registry.py
  src/anndata/experimental/__init__.py
Labels: topic: api, skip-gpu-ci

#1615 Backport PR #1612 on branch 0.10.x ((fix): use correct implementation of `StorageType` and resolve name conflict)
  src/anndata/_core/storage.py
  src/anndata/_io/specs/registry.py
  src/anndata/experimental/__init__.py
Labels: topic: api, skip-gpu-ci

#1596 GPU tests: install with uv
  .github/workflows/test-gpu.yml
  ci/gpu_ci.yml
  docs/release-notes/1596.dev.md
  pyproject.toml
Labels: topic: gpu, run-gpu-ci

#1619 (chore): prepare release notes
  docs/release-notes/0.10.9.md
  docs/release-notes/1147.bugfix.md
  docs/release-notes/1501.bugfix.md
  docs/release-notes/1504.performance.md
  docs/release-notes/1516.bugfix.md
  docs/release-notes/1532.bugfix.md
  docs/release-notes/1540.bugfix.md
  docs/release-notes/1557.doc.md
  docs/release-notes/1580.bugfix.md
  docs/release-notes/1586.bugfix.md
  docs/release-notes/1589.bugfix.md
  docs/release-notes/1596.dev.md
Labels: skip-gpu-ci

#1625 Run towncrier when building docs
  .readthedocs.yml
  docs/extensions/release_notes.py
  docs/release-notes/0.10.1.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.10.3.md
  docs/release-notes/0.10.4.md
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  docs/release-notes/0.10.7.md
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/0.7.6.md
  docs/release-notes/0.9.1.md
  docs/release-notes/0.9.2.md
  pyproject.toml
Labels: skip-gpu-ci

#1629 Backport PR #1625 on branch 0.10.x (Run towncrier when building docs)
  .readthedocs.yml
  docs/extensions/release_notes.py
  docs/release-notes/0.10.1.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.10.3.md
  docs/release-notes/0.10.4.md
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  docs/release-notes/0.10.7.md
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/0.7.6.md
  docs/release-notes/0.9.1.md
  docs/release-notes/0.9.2.md
  pyproject.toml
Labels: skip-gpu-ci

#1631 (refactor): `should`->`shall` in `settings`
  docs/release-notes/1340.feature.md
  docs/release-notes/1507.feature.md
  src/anndata/_core/anndata.py
  src/anndata/_settings.py
  tests/test_base.py
Labels: skip-gpu-ci

#1558 IO for nullable string arrays
  .azure-pipelines.yml
  docs/release-notes/1558.feature.md
  pyproject.toml
  src/anndata/_io/specs/methods.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/tests/helpers.py
  src/testing/anndata/_pytest.py
  tests/test_concatenate.py
  tests/test_helpers.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1616 (fix): correct typing of `AnnData.X`
  docs/concatenation.rst
  docs/release-notes/1616.doc.md
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/storage.py
  src/anndata/_types.py
  tests/test_base.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_x.py
Labels: skip-gpu-ci

#1632 Backport PR #1616 on branch 0.10.x ((fix): correct typing of AnnData.X)
  docs/concatenation.rst
  docs/release-notes/1616.doc.md
  hatch.toml
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/storage.py
  src/anndata/_types.py
  tests/test_base.py
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
  tests/test_x.py
Labels: skip-gpu-ci

#1598 (chore): export `read_elem` and `write_elem` from the main package
  benchmarks/benchmarks/sparse_dataset.py
  docs/api.md
  docs/conf.py
  docs/fileformat-prose.md
  docs/release-notes/0.10.0.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.8.0.md
  docs/release-notes/1598.feature.md
  docs/release-notes/1616.doc.md
  src/anndata/__init__.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_types.py
  src/anndata/experimental/__init__.py
  tests/test_backed_sparse.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_deprecations.py
  tests/test_io_dispatched.py
  tests/test_io_utils.py
Labels: skip-gpu-ci

#1626 (chore): automation of towncrier release process
  ci/scripts/towncrier_automation.py
  docs/contributing.md
  hatch.toml
  pyproject.toml
  src/anndata/logging.py
Labels: skip-gpu-ci

#1608 (fix): clarify public backed sparse docstring/api
  src/anndata/_core/sparse_dataset.py
  tests/test_backed_sparse.py
  tests/test_deprecations.py
Labels: docs, topic: api, skip-gpu-ci
