Repository scverse/anndata, pull requests merged in 2024-07, with the labels that each got.

#1346 Switch from using rubric in release notes
  docs/conf.py
  docs/index.md
  docs/news.md
  docs/release-notes/0.10.0.md
  docs/release-notes/0.10.1.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.10.3.md
  docs/release-notes/0.10.4.md
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  docs/release-notes/0.10.7.md
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/0.11.0.md
  docs/release-notes/0.4.0.md
  docs/release-notes/0.5.0.md
  docs/release-notes/0.6.0.md
  docs/release-notes/0.6.x.md
  docs/release-notes/0.7.0.md
  docs/release-notes/0.7.2.md
  docs/release-notes/0.7.3.md
  docs/release-notes/0.7.4.md
  docs/release-notes/0.7.5.md
  docs/release-notes/0.7.6.md
  docs/release-notes/0.7.7.md
  docs/release-notes/0.7.8.md
  docs/release-notes/0.8.0.md
  docs/release-notes/0.8.1.md
  docs/release-notes/0.9.0.md
  docs/release-notes/0.9.1.md
  docs/release-notes/0.9.2.md
  docs/release-notes/index.md
  docs/release-notes/release-latest.md
Labels: docs, skip-gpu-ci

#1551 Backport PR #1346: Switch from using rubric in release notes
  docs/conf.py
  docs/index.md
  docs/news.md
  docs/release-notes/0.10.0.md
  docs/release-notes/0.10.1.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.10.3.md
  docs/release-notes/0.10.4.md
  docs/release-notes/0.10.5.md
  docs/release-notes/0.10.6.md
  docs/release-notes/0.10.7.md
  docs/release-notes/0.10.8.md
  docs/release-notes/0.10.9.md
  docs/release-notes/0.4.0.md
  docs/release-notes/0.5.0.md
  docs/release-notes/0.6.0.md
  docs/release-notes/0.6.x.md
  docs/release-notes/0.7.0.md
  docs/release-notes/0.7.2.md
  docs/release-notes/0.7.3.md
  docs/release-notes/0.7.4.md
  docs/release-notes/0.7.5.md
  docs/release-notes/0.7.6.md
  docs/release-notes/0.7.7.md
  docs/release-notes/0.7.8.md
  docs/release-notes/0.8.0.md
  docs/release-notes/0.8.1.md
  docs/release-notes/0.9.0.md
  docs/release-notes/0.9.1.md
  docs/release-notes/0.9.2.md
  docs/release-notes/index.md
  docs/release-notes/release-latest.md
Labels: skip-gpu-ci

#1553 Backport PR #1552 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .github/workflows/check-pr-milestoned.yml
  .pre-commit-config.yaml
  tests/test_obsmvarm.py
  tests/test_obspvarp.py
Labels: dev process, skip-gpu-ci

#1504 (feat): allow `join=outer` for `concat_on_disk`
  docs/release-notes/0.10.9.md
  src/anndata/experimental/merge.py
  tests/test_concatenate_disk.py
Labels: enhancement, topic: combining, backend: hdf5, topic: backed, backend: zarr, skip-gpu-ci

#1501 (fix): add warning for setting `X` on view with repeat indices
  docs/release-notes/0.10.9.md
  src/anndata/_core/anndata.py
  tests/test_x.py
Labels: topic: views 👀, Bug 🐛, skip-gpu-ci

#1523 Fix sparse dataset 2D slicing
  src/anndata/_core/sparse_dataset.py
  tests/test_backed_sparse.py
Labels: skip-gpu-ci

#1554 Backport PR #1523 on branch 0.10.x (Fix sparse dataset 2D slicing)
  src/anndata/_core/sparse_dataset.py
  tests/test_backed_sparse.py
Labels: skip-gpu-ci

#1555 Backport PR #1501 on branch 0.10.x ((fix): add warning for setting X on view with repeat indices)
  docs/release-notes/0.10.9.md
  src/anndata/_core/anndata.py
  tests/test_x.py
Labels: skip-gpu-ci

#1556 Backport PR #1504 on branch 0.10.x ((feat): allow join=outer for concat_on_disk)
  docs/release-notes/0.10.9.md
  src/anndata/experimental/merge.py
  tests/test_concatenate_disk.py
Labels: skip-gpu-ci

#1559 Cleanup types
  pyproject.toml
  src/anndata/_core/aligned_df.py
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/storage.py
  src/anndata/_core/views.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/_settings.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/_dispatch_io.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1560 Backport PR #1559: Cleanup types
  pyproject.toml
  src/anndata/_core/aligned_df.py
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/storage.py
  src/anndata/_core/views.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/_dispatch_io.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1562 Backport PR #1561 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1557 (feat): add `callback` typing for `{read,write}_dispatched`
  docs/api.md
  docs/conf.py
  docs/release-notes/0.10.9.md
  pyproject.toml
  src/anndata/_io/h5ad.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_types.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/__init__.py
  src/anndata/experimental/_dispatch_io.py
Labels: skip-gpu-ci

#1563 Backport PR #1557 on branch 0.10.x ((feat): add `callback` typing for `{read,write}_dispatched`)
  docs/api.md
  docs/conf.py
  docs/release-notes/0.10.9.md
  pyproject.toml
  src/anndata/_io/h5ad.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_types.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/__init__.py
  src/anndata/experimental/_dispatch_io.py
Labels: skip-gpu-ci

#1550 (feat): allow writing from `cupy` inside `dask` arrays
  .github/workflows/test-gpu.yml
  docs/conf.py
  docs/release-notes/0.11.0.md
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/compat/__init__.py
  src/anndata/tests/helpers.py
  tests/test_dask.py
  tests/test_helpers.py
  tests/test_io_elementwise.py
Labels: run-gpu-ci

#1119 Fix garbage collection
  benchmarks/benchmarks/anndata.py
  docs/_templates/autosummary/class.rst
  docs/conf.py
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_core/raw.py
  src/anndata/_io/write.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  tests/test_base.py
  tests/test_layers.py
Labels: skip-gpu-ci, benchmark

#1568 Backport PR #1565 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1469 (feat): `read_elem_as_dask` method
  docs/api.md
  docs/release-notes/0.11.0.md
  pyproject.toml
  src/anndata/_core/file_backing.py
  src/anndata/_io/specs/__init__.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_types.py
  src/anndata/experimental/__init__.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1570 Backport PR #1569 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci
