Repository scverse/anndata, pull requests merged in 2024-01, with the labels that each got.

#1273 Fix IO error reporting
  .pre-commit-config.yaml
  anndata/_core/anndata.py
  anndata/_io/h5ad.py
  anndata/_io/specs/registry.py
  anndata/_io/utils.py
  anndata/_io/zarr.py
  anndata/compat/__init__.py
  anndata/experimental/_dispatch_io.py
  anndata/tests/test_awkward.py
  anndata/tests/test_io_utils.py
  anndata/tests/test_readwrite.py
  docs/release-notes/0.10.4.md
  pyproject.toml
Labels: run-gpu-ci

#1281 Backport PR #1273 on branch 0.10.x (Fix IO error reporting)
  .pre-commit-config.yaml
  anndata/_core/anndata.py
  anndata/_io/h5ad.py
  anndata/_io/specs/registry.py
  anndata/_io/utils.py
  anndata/_io/zarr.py
  anndata/compat/__init__.py
  anndata/experimental/_dispatch_io.py
  anndata/tests/test_awkward.py
  anndata/tests/test_io_utils.py
  anndata/tests/test_readwrite.py
  docs/release-notes/0.10.4.md
  pyproject.toml
Labels: skip-gpu-ci

#1280 Prepare v0.10.4 release
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1282 Backport PR #1280 on branch 0.10.x (Prepare v0.10.4 release)
  docs/release-notes/0.10.4.md
Labels: skip-gpu-ci

#1283 Start 0.10.5
  docs/release-notes/0.10.5.md
  docs/release-notes/release-latest.md
Labels: run-gpu-ci

#1284 Backport PR #1283 on branch 0.10.x (Start 0.10.5)
  docs/release-notes/0.10.5.md
  docs/release-notes/release-latest.md
Labels: run-gpu-ci

#1290 Backport PR #1289 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1291 Fix outer concatenation along axis=1 for missing layers
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.5.md
Labels: topic: combining, Bug 🐛, run-gpu-ci

#1294 Backport PR #1233 on branch 0.10.x ((fix): indexing performance in `backed` mode for `boolean` case)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
  benchmarks/benchmarks/sparse_dataset.py
  docs/release-notes/0.10.5.md
Labels: performance 🐌, topic: backed, backend: zarr, skip-gpu-ci

#1292 Backport PR #1291 on branch 0.10.x (Fix outer concatenation along axis=1 for missing layers)
  anndata/_core/merge.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.5.md
Labels: topic: combining, Bug 🐛, run-gpu-ci

#1266 (fix): cache `indptr` for backed sparse matrices
  anndata/_core/sparse_dataset.py
  anndata/tests/helpers.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.5.md
Labels: topic: backed, Bug 🐛, run-gpu-ci

#1296 Backport PR #1266 on branch 0.10.x ((fix): cache `indptr` for backed sparse matrices)
  anndata/_core/sparse_dataset.py
  anndata/tests/helpers.py
  anndata/tests/test_backed_sparse.py
  docs/release-notes/0.10.5.md
Labels: topic: backed, Bug 🐛, run-gpu-ci

#1298 Fix test compatibility with Pytest 8
  anndata/tests/test_io_warnings.py
  conftest.py
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1295 Skip type checking blocks when measuring coverage
  .pre-commit-config.yaml
  pyproject.toml
Labels: dev process, run-gpu-ci

#1299 Backport PR #1295 on branch 0.10.x (Skip type checking blocks when measuring coverage)
  .pre-commit-config.yaml
  pyproject.toml
Labels: dev process, run-gpu-ci

#1305 Pin against awkward array 2.5.2
  pyproject.toml
Labels: upstream, Bug 🐛, dev process, type: awkward array 😐, skip-gpu-ci

#1306 Backport PR #1305 on branch 0.10.x (Pin against awkward array 2.5.2)
  pyproject.toml
Labels: upstream, Bug 🐛, dev process, type: awkward array 😐, skip-gpu-ci

#1303 Remove unused and wrong test
  anndata/tests/test_readwrite.py
Labels: testing, dev process, skip-gpu-ci

#1302 Fix uns merge 3d
  anndata/_core/merge.py
  anndata/tests/helpers.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.5.md
Labels: topic: combining, Bug 🐛, run-gpu-ci

#1308 Backport PR #1302 on branch 0.10.x (Fix uns merge 3d)
  anndata/_core/merge.py
  anndata/tests/helpers.py
  anndata/tests/test_concatenate.py
  docs/release-notes/0.10.5.md
Labels: topic: combining, Bug 🐛, run-gpu-ci

#1310 Backport PR #1309 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1311 add readthedocs-sphinx-search
  docs/conf.py
  docs/release-notes/0.10.5.md
  pyproject.toml
Labels: skip-gpu-ci

#1312 Backport PR #1311 on branch 0.10.x (add readthedocs-sphinx-search)
  docs/conf.py
  docs/release-notes/0.10.5.md
  pyproject.toml
Labels: skip-gpu-ci

#1313 Fix a warning
  anndata/tests/test_dask_view_mem.py
Labels: dev process, skip-gpu-ci

#1326 Backport PR #1298 on branch 0.10.x (Fix test compatibility with Pytest 8)
  anndata/tests/test_io_warnings.py
  conftest.py
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1325 Backport PR #1324 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1327 Backport PR #1319 on branch 0.10.x ((fix): `SparseDataset` handles boolean mask containing one group)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
Labels: performance 🐌, Bug 🐛, skip-gpu-ci

#1328 Better fix for awkward 2.5.2
  anndata/_io/specs/methods.py
  docs/release-notes/0.10.5.md
  pyproject.toml
Labels: topic: io, type: awkward array 😐, skip-gpu-ci

#1332 Test for indexing with lists
  anndata/_core/index.py
  anndata/tests/helpers.py
  anndata/tests/test_hdf5_backing.py
  anndata/tests/test_views.py
  docs/release-notes/0.10.5.md
Labels: topic: indexing, Bug 🐛, run-gpu-ci

#1334 Backport PR #1332 on branch 0.10.x (Test for indexing with lists)
  anndata/_core/index.py
  anndata/tests/helpers.py
  anndata/tests/test_hdf5_backing.py
  anndata/tests/test_views.py
  docs/release-notes/0.10.5.md
Labels: topic: indexing, Bug 🐛, run-gpu-ci

#1321 (fix): empty boolean mask on backed sparse matrix
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
Labels: Bug 🐛, skip-gpu-ci

#1336 Backport PR #1321 on branch 0.10.x ((fix): empty boolean mask on backed sparse matrix)
  anndata/_core/sparse_dataset.py
  anndata/tests/test_backed_sparse.py
Labels: Bug 🐛, skip-gpu-ci

#1337 Prep 0.10.5
  docs/release-notes/0.10.5.md
Labels: dev process, run-gpu-ci

#1338 Backport PR #1337 on branch 0.10.x (Prep 0.10.5)
  docs/release-notes/0.10.5.md
Labels: dev process, run-gpu-ci

#1339 Run CI on release branches
  .azure-pipelines.yml
  .github/workflows/benchmark.yml
  .github/workflows/test-gpu.yml
Labels: dev process, run-gpu-ci

#1345 Backport PR #1341 on branch 0.10.x (Start 0.10.6)
  docs/release-notes/0.10.6.md
  docs/release-notes/release-latest.md
Labels: docs, dev process, skip-gpu-ci

#1344 Backport PR #1339 on branch 0.10.x (Run CI on release branches)
  .azure-pipelines.yml
  .github/workflows/benchmark.yml
  .github/workflows/test-gpu.yml
Labels: dev process, run-gpu-ci

#1343 (fix): move zarr import inside try-catch in test helpers
  anndata/tests/helpers.py
  docs/release-notes/0.10.6.md
Labels: backend: zarr, Bug 🐛, skip-gpu-ci

#1347 Backport PR #1343 on branch 0.10.x ((fix): move zarr import inside try-catch in test helpers)
  anndata/tests/helpers.py
  docs/release-notes/0.10.6.md
Labels: backend: zarr, Bug 🐛, skip-gpu-ci

#1335 Error on shared column names when writing
  anndata/_io/specs/methods.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.6.md
Labels: topic: io, type: dataframe 🧮, skip-gpu-ci

#1351 Backport PR #1335 on branch 0.10.x (Error on shared column names when writing)
  anndata/_io/specs/methods.py
  anndata/tests/test_io_elementwise.py
  docs/release-notes/0.10.6.md
Labels: topic: io, type: dataframe 🧮, skip-gpu-ci

#1270 (feat): add methods for changing settings
  anndata/__init__.py
  anndata/_config.py
  anndata/tests/test_config.py
  docs/api.md
  docs/release-notes/0.11.0.md
Labels: enhancement, topic: api, skip-gpu-ci
