Repository scverse/anndata, pull requests merged in 2024-09, with the labels that each got.

#1633 (feat): allow reading of `scipy.sparse.cs{c,r}_array`
  docs/release-notes/1633.feature.md
  src/anndata/_core/sparse_dataset.py
  src/anndata/_settings.py
  tests/test_backed_sparse.py
  tests/test_io_elementwise.py
  tests/test_settings.py
Labels: skip-gpu-ci

#1627 Add hatch-test env customization
  hatch.toml
Labels: skip-gpu-ci

#1636 Backport PR #1627 on branch 0.10.x (Add hatch-test env customization)
  hatch.toml
Labels: skip-gpu-ci

#1640 Backport PR #1639 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1643 (chore): `RWAble` → `AxisStorable`, `InMemoryElem` → `RWAble`
  docs/api.md
  docs/conf.py
  docs/release-notes/1643.breaking.md
  src/anndata/__init__.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_types.py
  src/anndata/experimental/__init__.py
  src/anndata/experimental/_dispatch_io.py
  tests/test_deprecations.py
Labels: topic: api, skip-gpu-ci

#1644 Reorder IO docs
  docs/api.md
Labels: skip-gpu-ci

#1645 add `.abc` and `.typing` modules
  docs/api.md
  docs/conf.py
  docs/extensions/no_skip_abc_members.py
  docs/release-notes/0.10.0.md
  docs/release-notes/0.10.2.md
  docs/release-notes/1616.doc.md
  docs/release-notes/1643.breaking.md
  src/anndata/__init__.py
  src/anndata/_core/anndata.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/storage.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_types.py
  src/anndata/abc.py
  src/anndata/experimental/__init__.py
  src/anndata/experimental/_dispatch_io.py
  src/anndata/typing.py
  tests/test_deprecations.py
Labels: skip-gpu-ci

#1650 (chore): fix docstring for `shall_use_sparse_array_on_read`
  src/anndata/_settings.py
Labels: docs, skip-gpu-ci

#1654 (fix): towncrier automation fixes
  ci/scripts/towncrier_automation.py
Labels: skip-gpu-ci

#1657 (chore): add `no-milestone` in case of `main`
  ci/scripts/towncrier_automation.py
Labels: skip-gpu-ci

#1664 (fix): regex for release notes on docs build
  docs/extensions/release_notes.py
Labels: skip-gpu-ci

#1671 Backport PR #1669 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#1672 Remove sphinx-toolbox patch
  docs/conf.py
  docs/extensions/patch_sphinx_toolbox_autoprotocol.py
  pyproject.toml
Labels: skip-gpu-ci

#1673 Upstream release-notes directive
  docs/conf.py
  docs/extensions/release_notes.py
  pyproject.toml
Labels: skip-gpu-ci

#1674 Backport PR #1673: Upstream release-notes directive
  docs/conf.py
  docs/extensions/release_notes.py
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1668 Revert uglification of CLI options
  ci/scripts/min-deps.py
  ci/scripts/towncrier_automation.py
Labels: skip-gpu-ci

#1676 Backport PR #1675 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1678 Fix towncrier Git CLI call
  ci/scripts/towncrier_automation.py
Labels: dev process, skip-gpu-ci

#1680 Fix VCS-derived version
  pyproject.toml
Labels: skip-gpu-ci

#1648 (chore): add `Index` type to `__getitem__` for sparse dataset
  docs/api.md
  docs/conf.py
  src/anndata/abc.py
  src/anndata/typing.py
Labels: skip-gpu-ci

#1685 (fix): remove `shall_` in boolean names
  docs/release-notes/0.11.0rc1.md
  src/anndata/_core/anndata.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_settings.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_io_elementwise.py
  tests/test_settings.py
Labels: topic: api, skip-gpu-ci

#1686 Prefer using copies in .raw
  src/anndata/_core/anndata.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_deprecations.py
  tests/test_get_vector.py
  tests/test_gpu.py
  tests/test_io_conversion.py
  tests/test_io_elementwise.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_transpose.py
  tests/test_views.py
Labels: docs, skip-gpu-ci

#1689 Backport PR #1686 on branch 0.10.x (Prefer using copies in .raw)
  src/anndata/_core/anndata.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_deprecations.py
  tests/test_get_vector.py
  tests/test_gpu.py
  tests/test_io_conversion.py
  tests/test_io_elementwise.py
  tests/test_raw.py
  tests/test_readwrite.py
  tests/test_transpose.py
  tests/test_views.py
Labels: docs, skip-gpu-ci

#1688 document zarr functions properly
  docs/conf.py
  src/anndata/io.py
Labels: skip-gpu-ci

#1691 Backport PR #1690 on branch 0.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1682 (feat): `io` submodule
  README.md
  docs/api.md
  docs/benchmark-read-write.ipynb
  docs/conf.py
  docs/fileformat-prose.md
  docs/release-notes/0.10.0.md
  docs/release-notes/0.10.2.md
  docs/release-notes/0.10.8.md
  docs/release-notes/0.11.0rc1.md
  docs/release-notes/0.5.0.md
  docs/release-notes/0.6.x.md
  docs/release-notes/0.7.6.md
  docs/release-notes/0.8.0.md
  docs/release-notes/0.9.0.md
  docs/release-notes/0.9.2.md
  docs/release-notes/1682.feat.md
  src/anndata/__init__.py
  src/anndata/_core/anndata.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/__init__.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_types.py
  src/anndata/experimental/__init__.py
  src/anndata/io.py
  src/anndata/typing.py
  src/anndata/utils.py
  src/testing/anndata/_pytest.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_deprecations.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_io_utils.py
  tests/test_io_warnings.py
  tests/test_readwrite.py
Labels: topic: io, skip-gpu-ci

#1692 Fix typing for optional imports
  docs/conf.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/pytorch/_annloader.py
  src/anndata/io.py
  src/anndata/tests/helpers.py
Labels: dev process, run-gpu-ci

#1693 (chore): generate 0.11.0rc2 release notes
  docs/release-notes/0.11.0rc2.md
  docs/release-notes/1677.dev.md
  docs/release-notes/1685.dev.md
Labels: no milestone, skip-gpu-ci

#1698 (chore): clean up release notes
  docs/release-notes/0.11.0rc1.md
  docs/release-notes/0.11.0rc2.md
  docs/release-notes/1682.feat.md
Labels: skip-gpu-ci
