Repository scverse/anndata, pull requests merged in 2025-07, with the labels that each got.

#2027 feat: add typing for the `settings` object
  pyproject.toml
  src/anndata/_settings.py
  src/anndata/_settings.pyi
  tests/test_settings.py
Labels: skip-gpu-ci

#2031 (chore): generate 0.12.0 release notes
  docs/release-notes/0.12.0.md
  docs/release-notes/2018.bugfix.md
Labels: no milestone, skip-gpu-ci

#2037 chore: clean up release notes
  docs/release-notes/0.12.0.md
  docs/release-notes/0.12.0rc1.md
  docs/release-notes/0.12.0rc2.md
  docs/release-notes/0.12.0rc3.md
  docs/release-notes/0.12.0rc4.md
  pyproject.toml
Labels: skip-gpu-ci

#2042 Backport PR #2041 on branch 0.12.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#2033 fix: chunking for lazy reading
  benchmarks/benchmarks/dataset2d.py
  docs/release-notes/2033.bugfix.md
  src/anndata/_io/specs/lazy_methods.py
  tests/lazy/test_read.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci, benchmark

#2046 (chore): generate 0.12.1 release notes
  docs/release-notes/0.12.1.md
  docs/release-notes/2033.bugfix.md
  docs/release-notes/2035.performance.md
Labels: skip-gpu-ci

#2051 fix: allow writing to v3/2 store when setting is v2/3 if possible
  docs/tutorials/zarr-v3.md
  src/anndata/_io/specs/methods.py
  src/anndata/_settings.py
  src/anndata/compat/__init__.py
  tests/test_backed_sparse.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#2050 Fix suggested branch to verify in bug issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: skip-gpu-ci

#2067 Fix index types
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/_core/raw.py
  src/anndata/_core/views.py
  src/anndata/_core/xarray.py
  src/anndata/compat/__init__.py
  src/anndata/tests/helpers.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_views.py
Labels: skip-gpu-ci
