Repository scverse/anndata, pull requests merged in 2025-01, with the labels that each got.

#1812 (chore): generate 0.11.2 release notes
  docs/release-notes/0.11.2.md
  docs/release-notes/1744.bugfix.md
  docs/release-notes/1746.bugfix.md
  docs/release-notes/1783.bugfix.md
  docs/release-notes/1790.performance.md
  docs/release-notes/1806.bugfix.md
Labels: skip-gpu-ci

#1820 (fix): remove `loompy` xfail
  src/testing/anndata/_helpers.py
  tests/test_layers.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1819 (fix): upper bound zarr at runtime (and in docs + benchmark)
  benchmarks/asv.conf.json
  docs/conf.py
  docs/release-notes/1819.bugfix.md
  pyproject.toml
  src/anndata/compat/__init__.py
Labels: skip-gpu-ci

#1822 Backport PR #1819 on branch 0.11.x ((fix): upper bound zarr at runtime (and in docs + benchmark))
  benchmarks/asv.conf.json
  docs/conf.py
  docs/release-notes/1819.bugfix.md
  pyproject.toml
  src/anndata/compat/__init__.py
Labels: skip-gpu-ci

#1821 Backport PR #1820 on branch 0.11.x ((fix): remove `loompy` xfail)
  src/testing/anndata/_helpers.py
  tests/test_layers.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1823 (chore): generate 0.11.3 release notes
  docs/release-notes/0.11.3.md
  docs/release-notes/1819.bugfix.md
Labels: skip-gpu-ci

#1824 Backport PR #1823 on branch main ((chore): generate 0.11.3 release notes)
  docs/release-notes/0.11.3.md
  docs/release-notes/1819.bugfix.md
Labels: no milestone, skip-gpu-ci

#1825 (chore): Update to Ruff 0.9 and add EM lints
  .pre-commit-config.yaml
  benchmarks/benchmarks/utils.py
  ci/scripts/min-deps.py
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_core/aligned_df.py
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/views.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/_settings.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/experimental/pytorch/_annloader.py
  src/anndata/io.py
  src/anndata/logging.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_helpers.py
  tests/test_layers.py
  tests/test_readwrite.py
  tests/test_settings.py
Labels: skip-gpu-ci

#1828 Backport PR #1825 on branch 0.11.x ((chore): Update to Ruff 0.9 and add EM lints)
  .pre-commit-config.yaml
  benchmarks/benchmarks/utils.py
  ci/scripts/min-deps.py
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_core/aligned_df.py
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/views.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/_settings.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/experimental/pytorch/_annloader.py
  src/anndata/io.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_helpers.py
  tests/test_layers.py
  tests/test_readwrite.py
  tests/test_settings.py
Labels: skip-gpu-ci

#1829 (chore): disallow `AnnData(...)` with non-csr{r,c} matrices/arrays
  docs/release-notes/1829.breaking.md
  src/anndata/_core/storage.py
  tests/test_x.py
Labels: type: sparse 🫥, skip-gpu-ci

#1831 (chore): Update version number inference in dev environments
  .gitignore
  docs/release-notes/1831.dev.md
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_version.py
Labels: skip-gpu-ci

#1830 (docs): Qualname-override everything we can
  docs/conf.py
  pyproject.toml
Labels: docs, dev process, skip-gpu-ci

#1832 Backport PR #1831 on branch 0.11.x ((chore): Update version number inference in dev environments)
  .gitignore
  docs/release-notes/1831.dev.md
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_version.py
Labels: skip-gpu-ci

#1833 Backport PR #1830 on branch 0.11.x ((docs): Qualname-override everything we can)
  docs/conf.py
  pyproject.toml
Labels: docs, dev process, skip-gpu-ci

#1836 Backport PR #1835 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: dev process, skip-gpu-ci

#999 Serialize Nones
  docs/release-notes/999.feature.md
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  tests/test_io_elementwise.py
  tests/test_readwrite.py
Labels: enhancement, topic: io, skip-gpu-ci

#1845 Backport PR #1844 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci
