Repository scverse/anndata, pull requests merged in 2025-04, with the labels that each got.

#1957 Patch sphinx_issues
  docs/extensions/patch_sphinx_issues.py
  docs/tutorials/zarr-v3.md
Labels: skip-gpu-ci

#1956 (chore): cleanup docs
  docs/extensions/patch_sphinx_issues.py
  docs/release-notes/0.11.1.md
  docs/release-notes/0.11.2.md
  docs/release-notes/0.11.3.md
  docs/release-notes/0.11.4.md
  docs/release-notes/0.12.0rc1.md
Labels: skip-gpu-ci

#1958 (chore): bump sphinx-issues
  docs/extensions/patch_sphinx_issues.py
  pyproject.toml
Labels: skip-gpu-ci

#1961 Add Pylint lints
  .pre-commit-config.yaml
  docs/extensions/no_skip_abc_members.py
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/utils.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/_types.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/backed/_io.py
  src/anndata/experimental/backed/_lazy_arrays.py
  src/anndata/experimental/backed/_xarray.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_base.py
  tests/test_extensions.py
  tests/test_settings.py
Labels: skip-gpu-ci, needs retroactive review

#1963 (chore): Add SIM lints
  docs/conf.py
  pyproject.toml
  src/anndata/_core/aligned_df.py
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/write.py
  src/anndata/_io/zarr.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/backed/_io.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/experimental/pytorch/_annloader.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_deprecations.py
  tests/test_io_backwards_compat.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_readwrite.py
  tests/test_views.py
Labels: skip-gpu-ci, needs retroactive review

#1964 (chore): Add BLE, C4, ISC, and PERF lints
  benchmarks/benchmarks/utils.py
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_core/access.py
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_io/write.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/tests/helpers.py
  src/anndata/utils.py
  src/testing/anndata/_pytest.py
  tests/test_transpose.py
  tests/test_views.py
Labels: skip-gpu-ci, needs retroactive review

#1965 (chore): Add RUF lints
  benchmarks/benchmarks/readwrite.py
  benchmarks/benchmarks/sparse_dataset.py
  pyproject.toml
  src/anndata/__init__.py
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/views.py
  src/anndata/_io/specs/__init__.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/abc.py
  src/anndata/experimental/__init__.py
  src/anndata/experimental/backed/_xarray.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/io.py
  src/anndata/tests/helpers.py
  src/anndata/typing.py
  tests/test_backed_sparse.py
  tests/test_concatenate.py
  tests/test_helpers.py
  tests/test_io_elementwise.py
  tests/test_x.py
Labels: skip-gpu-ci, needs retroactive review

#1962 (fix): convert 1d arrays to 2d for `xxxm`
  docs/release-notes/1962.bugfix.md
  src/anndata/_core/aligned_mapping.py
  tests/test_concatenate.py
  tests/test_obsmvarm.py
Labels: skip-gpu-ci

#1968 (chore): Remove old unused compat utilities
  src/anndata/_io/read.py
  src/anndata/compat/__init__.py
  src/anndata/tests/helpers.py
  tests/test_io_warnings.py
Labels: skip-gpu-ci

#1967 (chore): add bugbear and PIE lints
  pyproject.toml
  src/anndata/_core/aligned_df.py
  src/anndata/_core/anndata.py
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/storage.py
  src/anndata/_core/views.py
  src/anndata/_io/__init__.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/utils.py
  src/anndata/_io/write.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/_version.py
  src/anndata/_warnings.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/backed/_io.py
  src/anndata/experimental/merge.py
  src/anndata/experimental/multi_files/_anncollection.py
  src/anndata/utils.py
  tests/lazy/test_read.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_dask_view_mem.py
  tests/test_extensions.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_utils.py
  tests/test_repr.py
  tests/test_views.py
Labels: skip-gpu-ci, needs retroactive review

#1973 (fix): re-enable search popup
  docs/conf.py
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1976 (fix): `zarr` bound
  pyproject.toml
Labels: skip-gpu-ci

#1959 Load AnnLoader lazily to avoid torch imports when not requested
  docs/release-notes/1950.performance.md
  src/anndata/experimental/__init__.py
Labels: skip-gpu-ci

#1972 Catch all exceptions getting version from VCS, fallback to `importlib`
  src/anndata/_version.py
Labels: dev process, skip-gpu-ci

#1977 Backport PR #1972 on branch 0.11.x (Catch all exceptions getting version from VCS, fallback to importlib)
  src/anndata/_version.py
Labels: dev process, skip-gpu-ci
