Repository scverse/anndata, pull requests merged in 2025-03, with the labels that each got.

#1766 (chore): remove `anndata.read`
  docs/release-notes/1766.breaking.md
  pyproject.toml
  src/anndata/__init__.py
  tests/test_deprecations.py
Labels: skip-gpu-ci

#1889 Backport CS* tightening
  src/anndata/_core/aligned_mapping.py
  src/anndata/_core/anndata.py
  src/anndata/_core/index.py
  src/anndata/_core/merge.py
  src/anndata/_core/raw.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/_io/specs/methods.py
  src/anndata/abc.py
  src/anndata/compat/__init__.py
  src/anndata/typing.py
  tests/test_backed_hdf5.py
  tests/test_backed_sparse.py
  tests/test_base.py
  tests/test_concatenate.py
  tests/test_concatenate_disk.py
  tests/test_io_conversion.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1890 Fix coercion error for sparse arrays
  src/anndata/_core/merge.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_core/storage.py
  src/anndata/_io/specs/lazy_methods.py
  src/anndata/abc.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1726 (feat): support for `zarr-python>=3`
  docs/conf.py
  docs/fileformat-prose.md
  docs/release-notes/1726.feature.md
  pyproject.toml
  src/anndata/_core/anndata.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/abc.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/merge.py
  src/anndata/tests/helpers.py
  tests/conftest.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_io_backwards_compat.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_io_utils.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1888 (chore): `zarr` v3 updates for `xarray`
  docs/conf.py
  docs/fileformat-prose.md
  docs/release-notes/1726.feature.md
  pyproject.toml
  src/anndata/_core/anndata.py
  src/anndata/_core/sparse_dataset.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/specs/registry.py
  src/anndata/_io/utils.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/abc.py
  src/anndata/compat/__init__.py
  src/anndata/experimental/backed/_io.py
  src/anndata/experimental/backed/_lazy_arrays.py
  src/anndata/experimental/merge.py
  src/anndata/tests/helpers.py
  tests/conftest.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_concatenate_disk.py
  tests/test_dask.py
  tests/test_io_backwards_compat.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_io_utils.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1624 Chunked writing of h5py.Dataset and zarr.Array
  src/anndata/_io/specs/methods.py
  src/anndata/_settings.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1896 Backport PR #1886 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1898 Format TOML with taplo
  .pre-commit-config.yaml
  .taplo.toml
  hatch.toml
  pyproject.toml
Labels: skip-gpu-ci

#1893 Auto backport of pr 1624 on 0.11.x
  src/anndata/_io/specs/methods.py
  src/anndata/_settings.py
  tests/test_io_dispatched.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1900 "Backport PR #1898 on branch 0.11.x (Format TOML with taplo)"
  .pre-commit-config.yaml
  .taplo.toml
  hatch.toml
  pyproject.toml
Labels: skip-gpu-ci

#1885 Fix link URL in docstring
  src/anndata/_io/h5ad.py
Labels: skip-gpu-ci

#1905 Backport PR #1885 on branch 0.11.x (Fix link URL in docstring)
  src/anndata/_io/h5ad.py
Labels: skip-gpu-ci

#1909 Backport PR #1908 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1903 (chore): allow zarr v3 benchmarks
  benchmarks/asv.conf.json
Labels: skip-gpu-ci, benchmark

#1916 randomize test order
  pyproject.toml
Labels: dev process, skip-gpu-ci

#1918 (fix): correct workflow branch selection
  .github/workflows/test-cpu.yml
Labels: dev process, skip-gpu-ci

#1914 (fix): add `convert_strings_to_categoricals` to methods
  docs/api.md
  docs/conf.py
  docs/release-notes/1914.bugfix.md
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/write.py
  src/anndata/_io/zarr.py
  src/anndata/experimental/backed/_io.py
  src/anndata/experimental/merge.py
  tests/lazy/test_concat.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1920 Backport PR #1914 on branch 0.11.x ((fix): add convert_strings_to_categoricals to methods )
  docs/api.md
  docs/conf.py
  docs/release-notes/1914.bugfix.md
  src/anndata/_core/anndata.py
  src/anndata/_core/file_backing.py
  src/anndata/_io/h5ad.py
  src/anndata/_io/read.py
  src/anndata/_io/specs/methods.py
  src/anndata/_io/write.py
  src/anndata/_io/zarr.py
  src/anndata/experimental/merge.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1924 Use same local Dask cluster in tests
  pyproject.toml
  tests/conftest.py
  tests/lazy/test_concat.py
  tests/test_dask.py
  tests/test_io_elementwise.py
Labels: dev process, skip-gpu-ci

#1926 Backport PR #1924 on branch 0.11.x (Use same local Dask cluster in tests)
  pyproject.toml
  tests/conftest.py
  tests/test_dask.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1928 (chore): upgrade `__setitem__` warning for `BaseCompressedSparseDataset`
  docs/release-notes/1928.bugfix.md
  src/anndata/_core/sparse_dataset.py
  tests/test_backed_hdf5.py
Labels: skip-gpu-ci

#1933 (fix): no `asyncio.run` for clearing a store
  docs/release-notes/1933.bugfix.md
  src/anndata/_io/specs/registry.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1932 (fix): force `dask` cluster tests to be run in same process
  pyproject.toml
  tests/conftest.py
  tests/lazy/test_concat.py
  tests/test_dask.py
  tests/test_io_elementwise.py
Labels: skip-gpu-ci

#1911 fix outer concatenation along var when varm is not empty
  docs/release-notes/1911.bugfix.md
  src/anndata/_core/merge.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1936 Backport PR #1911 on branch 0.11.x (fix outer concatenation along var when varm is not empty)
  docs/release-notes/1911.bugfix.md
  src/anndata/_core/merge.py
  tests/test_concatenate.py
Labels: skip-gpu-ci

#1937 Backport PR #1934 on branch 0.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: skip-gpu-ci

#1938 (chore): generate 0.11.4 release notes
  docs/release-notes/0.11.4.md
  docs/release-notes/1831.dev.md
  docs/release-notes/1853.bugfix.md
  docs/release-notes/1859.bugfix.md
  docs/release-notes/1911.bugfix.md
  docs/release-notes/1914.bugfix.md
  docs/release-notes/1941.bugfix.md
Labels: skip-gpu-ci

#1940 (fix): disallow forward slash writes
  docs/release-notes/1940.bugfix.md
  src/anndata/_io/specs/registry.py
  tests/test_readwrite.py
Labels: skip-gpu-ci

#1939 Backport PR #1938 on branch main ((chore): generate 0.11.4 release notes)
  docs/release-notes/0.11.4.md
  docs/release-notes/1831.dev.md
  docs/release-notes/1853.bugfix.md
  docs/release-notes/1859.bugfix.md
  docs/release-notes/1911.bugfix.md
  docs/release-notes/1914.bugfix.md
  docs/release-notes/1941.bugfix.md
Labels: no milestone, skip-gpu-ci

#1941 Add linkable labels to API docs
  docs/api.md
Labels: skip-gpu-ci

#1942 Backport PR #1941 on branch 0.11.x (Add linkable labels to API docs)
  docs/api.md
Labels: skip-gpu-ci

#1892 (feat): allow zarr v3 writing
  docs/release-notes/1892.feature.md
  pyproject.toml
  src/anndata/_io/specs/methods.py
  src/anndata/_io/zarr.py
  src/anndata/_settings.py
  src/anndata/tests/helpers.py
  tests/conftest.py
  tests/test_backed_dense.py
  tests/test_backed_sparse.py
  tests/test_dask.py
  tests/test_io_backwards_compat.py
  tests/test_io_elementwise.py
  tests/test_io_partial.py
  tests/test_io_utils.py
  tests/test_readwrite.py
  tests/test_structured_arrays.py
  tests/test_x.py
Labels: skip-gpu-ci

#1943 (fix): download using `httpx.get`
  src/anndata/experimental/merge.py
Labels: skip-gpu-ci

#1944 (fix): use correct CI badge
  README.md
Labels: skip-gpu-ci

#1946 Backport PR #1944 on branch 0.11.x ((fix): use correct CI badge)
  README.md
Labels: skip-gpu-ci

#1870 Accessor Functionality for AnnData
  docs/api.md
  src/anndata/__init__.py
  src/anndata/_core/anndata.py
  src/anndata/_core/extensions.py
  src/anndata/_types.py
  src/anndata/types.py
  tests/test_extensions.py
Labels: skip-gpu-ci
